#!/usr/bin/env node
// Writes the current package.json version into a generated TS constant so the
// UI never hand-types a version string again. Runs as an npm "pre" hook before
// build/start — see package.json.
const fs = require('fs');
const path = require('path');

const pkg = require(path.join(__dirname, '..', 'package.json'));
const outFile = path.join(__dirname, '..', 'src', 'environments', 'version.ts');

const content = `// GENERATED by scripts/set-version.js — do not edit by hand.
export const APP_VERSION = '${pkg.version}';
`;

fs.writeFileSync(outFile, content);
console.log(`[set-version] wrote ${pkg.version} to ${path.relative(process.cwd(), outFile)}`);
