-- =============================================================================
-- Syncpoint Compliance — Demo Seed
--
-- Idempotent. Safe to run repeatedly against a running instance.
--
-- Produces a self-contained "Demo Corp" tenant covering all 15 SOC 2 demo
-- controls with a realistic mix of states:
--   * demo-owner@syncpoint.local     (password: demo-password-2026, role: OWNER, platform admin)
--   * demo-reviewer@syncpoint.local  (password: demo-password-2026, role: REVIEWER)
--   * demo-acknowledger@syncpoint.local (password: demo-password-2026, role: ACKNOWLEDGER —
--     restricted role that can only view/acknowledge My Policies, nothing else)
--   * demo-auditor@syncpoint.local (password: demo-password-2026, role: AUDITOR — the invited
--     external CPA firm, restricted to the read-only /auditor workspace + evidence-request/
--     mark-reviewed actions, access_expires_at ~90 days out to look like a real engagement)
--   * 4 policies covering the realistic mix: one fully mapped + acknowledged by the
--     acknowledger but still pending owner/reviewer, one with a mix of confirmed and
--     still-AI-suggested control mappings and zero acknowledgments, one freshly
--     published with no mappings or acknowledgments yet (a real gap), and one archived
--     policy that was fully acknowledged before being superseded
--   * 12 hand-authored evidence artifacts driving the exact coverage story below,
--     plus ~48 additional bulk evidence artifacts (mostly unmapped/backlog, some
--     expiring/expired, some AI-suggested) so Evidence/Review Queue have enough
--     rows to page through
--   * 7 controls COVERED (human-confirmed, approved evidence)
--   * 2 controls PARTIAL (human-confirmed, but only partial coverage)
--   * 3 controls NEEDS_REVIEW (AI-suggested, awaiting human confirmation)
--   * 3 controls MISSING (no evidence collected yet — realistic gaps)
--   * 14 days of coverage-trend history building up to that same result
--   * A PRO/ACTIVE subscription (25 seats) so the platform admin console
--     (visible to demo-owner) shows a paying customer, not just a bare trial
--   * 4 integrations (GitHub/AWS/Jira/Google Workspace) with ~48 historical
--     collection runs + items so the Activity page has real history
--   * ~200 audit events spanning the past ~90 days so the Audit Log has
--     enough rows to page through
--   * 14 additional fake customer organizations with varied plans/statuses
--     (including a few expiring-soon and past-due/suspended/canceled) plus
--     several subscription change requests, so the platform admin console's
--     organization table and renewal-request queue both have enough rows to
--     exercise pagination
--   * Compliance Program fully filled in (v0.8.0): Type II with a 6-month
--     observation period ending today, TSC scope Security+Availability+
--     Confidentiality, and all 6 system-description fields written out
--     (including CUEC and "significant changes during the period") so the
--     Readiness Report never shows a "(not yet documented)" placeholder
--   * 9 of 38 controls given a real owner (demo-owner or demo-reviewer) —
--     a realistic partial-completion state, not every control assigned
--   * 8 risks in the Risk Register (v0.8.0) spanning every category, every
--     status, and a full score range — including one HIGH/HIGH (9) risk
--     that's still IDENTIFIED and one risk with zero linked controls, so
--     the Readiness Report's "auditor gap" callouts have something to show.
--     Most are linked to the controls whose PARTIAL/NEEDS_REVIEW/MISSING
--     story above already implies a risk (CC6.1, CC6.7, CC8.1, CC9.1, CC9.2)
--   * 4 control exceptions (v0.8.0) within the observation period — 3
--     remediated, 1 still open — against controls that are otherwise
--     COVERED or NEEDS_REVIEW, demonstrating that "evidence exists" and
--     "nothing went wrong" are genuinely different questions
--   * Auditor firm profile filled in (Whitmore & Associates CPAs) plus one
--     open evidence request, one resolved review note, and two control
--     review marks from the seeded demo-auditor account, so the Auditor
--     workspace and the org-side "Auditor requests" inbox both have real
--     data on first login instead of empty states
--
-- Passwords are BCrypt-cost-12 hashes of the literal string above. They were
-- generated by the running backend and copied here so no bcrypt tooling is
-- required to install the seed.
--
-- Usage:
--   docker compose exec -T postgres psql -U compliance -d compliance \
--       < database/seed/demo.sql
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 0. Purge any existing demo state so the seed is fully idempotent.
-- -----------------------------------------------------------------------------

DELETE FROM organization_members
 WHERE user_id IN (
    SELECT id FROM users WHERE email IN
        ('demo-owner@syncpoint.local', 'demo-reviewer@syncpoint.local', 'demo-acknowledger@syncpoint.local', 'demo-auditor@syncpoint.local')
 );

DELETE FROM organizations WHERE slug LIKE 'demo-corp%';
DELETE FROM organizations WHERE slug LIKE 'reviewer-solo-org%';

-- Bulk fake customer organizations (section 8 below) + their owner accounts.
-- MUST run before deleting demo-owner: some of these orgs' historical
-- subscription_requests have demo-owner as reviewed_by (acting as platform
-- admin), and that foreign key has no ON DELETE action, so demo-owner can't
-- be deleted while it's still referenced.
DELETE FROM organizations WHERE slug LIKE 'demo-cust-%';
DELETE FROM users WHERE email LIKE '%@democustomer.example';

DELETE FROM users
 WHERE email IN ('demo-owner@syncpoint.local', 'demo-reviewer@syncpoint.local', 'demo-acknowledger@syncpoint.local', 'demo-auditor@syncpoint.local');

-- -----------------------------------------------------------------------------
-- 1. Core tenant entities. Fixed UUIDs keep the seed reproducible.
-- -----------------------------------------------------------------------------

INSERT INTO organizations (id, name, slug, onboarding_completed, onboarding_completed_at,
                           tsc_scope_extra, report_type, observation_period_start,
                           observation_period_end, target_report_date, services_provided,
                           system_boundaries, components_description, subservice_organizations,
                           complementary_user_entity_controls, significant_changes_during_period,
                           auditor_firm_name, auditor_contact_name, auditor_contact_email)
VALUES
    ('00000000-0000-4000-a000-000000000001', 'Demo Corp', 'demo-corp', TRUE, NOW(),
     'AVAILABILITY,CONFIDENTIALITY', 'TYPE_II',
     (NOW() - INTERVAL '6 months')::date, NOW()::date, (NOW() + INTERVAL '45 days')::date,
     'Demo Corp provides a SaaS platform that helps customers collect, map, and review SOC 2 compliance evidence, and generates audit-ready reports for their CPA firm.',
     'The system boundary includes the Demo Corp web application, API backend, and database, all hosted in a single AWS region (us-east-1). It excludes customer-owned infrastructure and any third-party systems Demo Corp integrates with (GitHub, AWS, Jira, Google Workspace) but does not operate.',
     'Infrastructure: AWS (EC2, RDS Postgres, S3). Software: a Java/Spring Boot API, an Angular web application, and a Python AI microservice for evidence-to-control mapping suggestions. People: a 12-person engineering and security team. Procedures: documented change-management, incident-response, and access-review procedures (see Policies). Data: customer-uploaded evidence artifacts and compliance metadata, encrypted at rest and in transit.',
     'Amazon Web Services, Inc. (cloud infrastructure hosting) and GitHub, Inc. (source code hosting for customer-authorized integrations). Both maintain their own SOC 2 Type II reports, available on request.',
     'Customers are responsible for: (1) maintaining the confidentiality of their own user credentials and API tokens configured in Demo Corp integrations; (2) promptly notifying Demo Corp of any suspected unauthorized access to their account; (3) configuring appropriate access roles for their own team members within the platform; and (4) reviewing and confirming AI-suggested evidence mappings rather than relying on them as final compliance determinations.',
     'Migrated the risk register and control-exception tracking features to production during the observation period. No changes to the production AWS account structure, encryption approach, or access-control model occurred during this period.',
     'Whitmore & Associates CPAs', 'Karen Whitmore', 'karen.whitmore@whitmoreassociates.example');

INSERT INTO users (id, email, password_hash, name, platform_admin) VALUES
    ('00000000-0000-4000-a000-000000000010',
     'demo-owner@syncpoint.local',
     '$2a$12$Lz86VSKdF6K7P4qd3LuQbOWudQKOsr6skAS5k2kExB4x3z8hdME6C',
     'Demo Owner', TRUE),
    ('00000000-0000-4000-a000-000000000011',
     'demo-reviewer@syncpoint.local',
     '$2a$12$NBZlfZ0TfiWsIVx1zb/D4.XdB.dtl5KSgjLxE9fp6otJs7kYTjbju',
     'Demo Reviewer', FALSE),
    ('00000000-0000-4000-a000-000000000012',
     'demo-acknowledger@syncpoint.local',
     '$2a$12$Lz86VSKdF6K7P4qd3LuQbOWudQKOsr6skAS5k2kExB4x3z8hdME6C',
     'Demo Acknowledger', FALSE),
    ('00000000-0000-4000-a000-000000000013',
     'demo-auditor@syncpoint.local',
     '$2a$12$Lz86VSKdF6K7P4qd3LuQbOWudQKOsr6skAS5k2kExB4x3z8hdME6C',
     'Karen Whitmore', FALSE);

INSERT INTO organization_members (organization_id, user_id, role, access_expires_at) VALUES
    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000010', 'OWNER', NULL),
    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000011', 'REVIEWER', NULL),
    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000012', 'ACKNOWLEDGER', NULL),
    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000013', 'AUDITOR', NOW() + INTERVAL '90 days');

-- Platform-admin console: give the demo tenant a real-looking paid subscription so the admin
-- console list isn't just a wall of fresh trials (V19's backfill row is cascade-deleted above
-- along with the org, so it must be re-seeded here every time this script runs).
INSERT INTO subscriptions (organization_id, plan, status, seat_limit, current_period_start, current_period_end) VALUES
    ('00000000-0000-4000-a000-000000000001', 'PRO', 'ACTIVE', 25, NOW() - INTERVAL '20 days', NOW() + INTERVAL '10 days');

-- A pending renewal/upgrade request so the platform admin's review queue isn't empty on a fresh seed.
INSERT INTO subscription_requests (organization_id, requested_by, requested_plan, requested_seat_limit, note) VALUES
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'ENTERPRISE', 50, 'Growing fast, need more seats and enterprise support.');


-- -----------------------------------------------------------------------------
-- 2. Sample evidence — one artifact per mapped control (12 of 15 originally-
--    curated controls; CC9.2 is deliberately left without evidence to
--    demonstrate a real gap. The control catalog was expanded to the full
--    38-control AICPA-structured set in R__seed_soc2_demo.sql -- the ~23
--    newly-added controls have no evidence yet and will show MISSING, which
--    is intentional rather than a fabricated coverage story.
--
--    NOTE: evidence_versions rows point at storage_keys that will not exist
--    in MinIO because this SQL seed does not upload bytes. The application
--    tolerates this: analyze / download paths log a warning and continue.
--    Real bytes can be attached by uploading the same-named files via the UI.
-- -----------------------------------------------------------------------------

WITH org AS (SELECT '00000000-0000-4000-a000-000000000001'::uuid AS id),
     usr AS (SELECT '00000000-0000-4000-a000-000000000010'::uuid AS id)
INSERT INTO evidence (id, organization_id, name, description, source_type,
                      source_system, status, collected_at, expires_at, created_by)
SELECT * FROM (VALUES
    -- CC6.3 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000100'::uuid,
     (SELECT id FROM org),
     'Q1-2026 Access Review',
     'Quarterly review of production IAM access. Signed by the security lead.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '3 days',
     NOW() + INTERVAL '362 days',
     (SELECT id FROM usr)),
    -- CC6.1 — AI-suggested only, deliberately unconfirmed → NEEDS_REVIEW
    ('00000000-0000-4000-a000-000000000101'::uuid,
     (SELECT id FROM org),
     'AWS IAM User List (export)',
     'CSV export of production IAM users and their role assignments.',
     'MANUAL_UPLOAD', 'manual-upload',
     'COLLECTED',
     NOW() - INTERVAL '2 days',
     NOW() + INTERVAL '363 days',
     (SELECT id FROM usr)),
    -- CC8.1 — AI-suggested only → NEEDS_REVIEW
    ('00000000-0000-4000-a000-000000000102'::uuid,
     (SELECT id FROM org),
     'Change Management Policy',
     'Written policy on branch protection, code review, and deploy approvals.',
     'MANUAL_UPLOAD', 'manual-upload',
     'COLLECTED',
     NOW() - INTERVAL '1 days',
     NOW() + INTERVAL '364 days',
     (SELECT id FROM usr)),
    -- CC6.2 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000103'::uuid,
     (SELECT id FROM org),
     'Access Request & Approval Log - Q1 2026',
     'Ticketing export showing manager-approved access grants for the current quarter.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '12 days',
     NOW() + INTERVAL '353 days',
     (SELECT id FROM usr)),
    -- CC6.6 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000104'::uuid,
     (SELECT id FROM org),
     'Okta MFA Enforcement Policy',
     'Org-wide policy document showing MFA is required for all privileged and remote access.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '9 days',
     NOW() + INTERVAL '356 days',
     (SELECT id FROM usr)),
    -- CC6.7 — human-confirmed PARTIAL
    ('00000000-0000-4000-a000-000000000105'::uuid,
     (SELECT id FROM org),
     'Encryption Configuration Export',
     'Automated export of encryption-at-rest and in-transit settings across production data stores.',
     'AWS', 'aws/prod-account',
     'UNDER_REVIEW',
     NOW() - INTERVAL '5 days',
     NOW() + INTERVAL '360 days',
     (SELECT id FROM usr)),
    -- CC7.1 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000106'::uuid,
     (SELECT id FROM org),
     'CloudWatch Monitoring Dashboard Export',
     'Snapshot of production monitoring dashboards and alerting configuration.',
     'AWS', 'aws/prod-account',
     'APPROVED',
     NOW() - INTERVAL '6 days',
     NOW() + INTERVAL '359 days',
     (SELECT id FROM usr)),
    -- CC7.2 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000107'::uuid,
     (SELECT id FROM org),
     'Incident Response Playbook v3.2',
     'Documented incident response process covering detection, escalation, and post-incident review.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '8 days',
     NOW() + INTERVAL '357 days',
     (SELECT id FROM usr)),
    -- CC9.1 — human-confirmed PARTIAL
    ('00000000-0000-4000-a000-000000000108'::uuid,
     (SELECT id FROM org),
     'Annual Risk Assessment 2025',
     'Risk register identifying and scoring risks to the business and its systems.',
     'MANUAL_UPLOAD', 'manual-upload',
     'UNDER_REVIEW',
     NOW() - INTERVAL '4 days',
     NOW() + INTERVAL '361 days',
     (SELECT id FROM usr)),
    -- A1.1 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000109'::uuid,
     (SELECT id FROM org),
     'Uptime & Status Page Export - Q1 2026',
     'Historical uptime and incident data from the public status page.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '11 days',
     NOW() + INTERVAL '354 days',
     (SELECT id FROM usr)),
    -- A1.2 — AI-suggested only → NEEDS_REVIEW
    ('00000000-0000-4000-a000-000000000110'::uuid,
     (SELECT id FROM org),
     'Backup Restore Test Report - Q4 2025',
     'Report from the most recent disaster-recovery restore test.',
     'MANUAL_UPLOAD', 'manual-upload',
     'COLLECTED',
     NOW() - INTERVAL '3 days',
     NOW() + INTERVAL '362 days',
     (SELECT id FROM usr)),
    -- C1.1 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000111'::uuid,
     (SELECT id FROM org),
     'Data Classification Policy v2',
     'Policy defining confidentiality tiers and required protections per tier.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '13 days',
     NOW() + INTERVAL '352 days',
     (SELECT id FROM usr))
) AS v(id, organization_id, name, description, source_type, source_system,
       status, collected_at, expires_at, created_by);

INSERT INTO evidence_versions (id, evidence_id, organization_id, version,
                               storage_key, content_hash, size_bytes,
                               mime_type, collector_version, collected_at)
VALUES
    ('00000000-0000-4000-a000-000000000200', '00000000-0000-4000-a000-000000000100',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000100/00000000-0000-4000-a000-000000000200',
     'demo-seed-hash-1000000000000000000000000000000000000000000000000000000',
     512, 'application/pdf', 'manual/1', NOW() - INTERVAL '3 days'),
    ('00000000-0000-4000-a000-000000000201', '00000000-0000-4000-a000-000000000101',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000101/00000000-0000-4000-a000-000000000201',
     'demo-seed-hash-1010000000000000000000000000000000000000000000000000000',
     2048, 'text/csv', 'manual/1', NOW() - INTERVAL '2 days'),
    ('00000000-0000-4000-a000-000000000202', '00000000-0000-4000-a000-000000000102',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000102/00000000-0000-4000-a000-000000000202',
     'demo-seed-hash-1020000000000000000000000000000000000000000000000000000',
     1024, 'application/pdf', 'manual/1', NOW() - INTERVAL '1 days'),
    ('00000000-0000-4000-a000-000000000203', '00000000-0000-4000-a000-000000000103',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000103/00000000-0000-4000-a000-000000000203',
     'demo-seed-hash-1030000000000000000000000000000000000000000000000000000',
     1536, 'application/pdf', 'manual/1', NOW() - INTERVAL '12 days'),
    ('00000000-0000-4000-a000-000000000204', '00000000-0000-4000-a000-000000000104',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000104/00000000-0000-4000-a000-000000000204',
     'demo-seed-hash-1040000000000000000000000000000000000000000000000000000',
     896, 'application/pdf', 'manual/1', NOW() - INTERVAL '9 days'),
    ('00000000-0000-4000-a000-000000000205', '00000000-0000-4000-a000-000000000105',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000105/00000000-0000-4000-a000-000000000205',
     'demo-seed-hash-1050000000000000000000000000000000000000000000000000000',
     4096, 'application/json', 'aws/1', NOW() - INTERVAL '5 days'),
    ('00000000-0000-4000-a000-000000000206', '00000000-0000-4000-a000-000000000106',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000106/00000000-0000-4000-a000-000000000206',
     'demo-seed-hash-1060000000000000000000000000000000000000000000000000000',
     5120, 'application/json', 'aws/1', NOW() - INTERVAL '6 days'),
    ('00000000-0000-4000-a000-000000000207', '00000000-0000-4000-a000-000000000107',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000107/00000000-0000-4000-a000-000000000207',
     'demo-seed-hash-1070000000000000000000000000000000000000000000000000000',
     8192, 'application/pdf', 'manual/1', NOW() - INTERVAL '8 days'),
    ('00000000-0000-4000-a000-000000000208', '00000000-0000-4000-a000-000000000108',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000108/00000000-0000-4000-a000-000000000208',
     'demo-seed-hash-1080000000000000000000000000000000000000000000000000000',
     2048, 'application/pdf', 'manual/1', NOW() - INTERVAL '4 days'),
    ('00000000-0000-4000-a000-000000000209', '00000000-0000-4000-a000-000000000109',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000109/00000000-0000-4000-a000-000000000209',
     'demo-seed-hash-1090000000000000000000000000000000000000000000000000000',
     1280, 'text/csv', 'manual/1', NOW() - INTERVAL '11 days'),
    ('00000000-0000-4000-a000-000000000210', '00000000-0000-4000-a000-000000000110',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000110/00000000-0000-4000-a000-000000000210',
     'demo-seed-hash-1100000000000000000000000000000000000000000000000000000',
     3584, 'application/pdf', 'manual/1', NOW() - INTERVAL '3 days'),
    ('00000000-0000-4000-a000-000000000211', '00000000-0000-4000-a000-000000000111',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000111/00000000-0000-4000-a000-000000000211',
     'demo-seed-hash-1110000000000000000000000000000000000000000000000000000',
     1024, 'application/pdf', 'manual/1', NOW() - INTERVAL '13 days');

-- -----------------------------------------------------------------------------
-- 3. Mappings — final tally across the 15 originally-curated controls:
--      7 COVERED (CC6.2, CC6.3, CC6.6, CC7.1, CC7.2, A1.1, C1.1)
--      2 PARTIAL (CC6.7, CC9.1)
--      3 NEEDS_REVIEW (CC6.1, CC8.1, A1.2)
--      1 MISSING (CC9.2 — no evidence collected yet)
--    Plus ~23 additional controls from the full AICPA catalog expansion,
--    all MISSING until real evidence is collected for them.
-- -----------------------------------------------------------------------------

INSERT INTO evidence_control_mappings (id, organization_id, evidence_id,
                                       control_id, mapping_type, classification,
                                       confidence, reason, created_by)
SELECT m.id, m.organization_id, m.evidence_id, c.id, m.mapping_type, m.classification,
       m.confidence, m.reason, m.created_by
FROM (VALUES
    ('00000000-0000-4000-a000-000000000300'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000100'::uuid, 'CC6.3',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: signed quarterly access review is present.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000301'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000101'::uuid, 'CC6.1',
     'AI_SUGGESTED', 'PARTIAL', 0.720,
     'Evidence lists current IAM users but does not demonstrate a periodic review or approval trail.',
     NULL),
    ('00000000-0000-4000-a000-000000000302'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000102'::uuid, 'CC8.1',
     'AI_SUGGESTED', 'PARTIAL', 0.680,
     'Policy document exists but does not demonstrate that the peer-review process is consistently followed.',
     NULL),
    ('00000000-0000-4000-a000-000000000303'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000103'::uuid, 'CC6.2',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: every sampled access grant has a matching approval ticket.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000304'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000104'::uuid, 'CC6.6',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: MFA is enforced org-wide with no exceptions found.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000305'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000105'::uuid, 'CC6.7',
     'HUMAN_CONFIRMED', 'PARTIAL', 0.750,
     'Reviewer confirmed encryption-at-rest is enforced, but in-transit configuration for two internal services is still unverified.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000306'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000106'::uuid, 'CC7.1',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: dashboards and alerting cover all production services.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000307'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000107'::uuid, 'CC7.2',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: playbook covers detection through post-incident review.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000308'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000108'::uuid, 'CC9.1',
     'HUMAN_CONFIRMED', 'PARTIAL', 0.700,
     'Reviewer confirmed the risk register exists, but treatment plans for two identified risks are still in progress.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000309'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000109'::uuid, 'A1.1',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: uptime history matches the committed availability target.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000310'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000110'::uuid, 'A1.2',
     'AI_SUGGESTED', 'PARTIAL', 0.650,
     'Restore test report is present but does not confirm the recovery time objective was met.',
     NULL),
    ('00000000-0000-4000-a000-000000000311'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000111'::uuid, 'C1.1',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: classification tiers and protections are clearly defined.',
     '00000000-0000-4000-a000-000000000011'::uuid)
) AS m(id, organization_id, evidence_id, control_code, mapping_type, classification,
       confidence, reason, created_by)
JOIN controls c ON c.code = m.control_code;

-- -----------------------------------------------------------------------------
-- 4. Reviews for every APPROVED evidence artifact above.
-- -----------------------------------------------------------------------------

INSERT INTO evidence_reviews (id, organization_id, evidence_id, reviewer_id,
                              decision, comments)
VALUES
    ('00000000-0000-4000-a000-000000000400', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000100', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Signed by security lead; scope and dates check out.'),
    ('00000000-0000-4000-a000-000000000401', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000103', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Ticket export matches sampled access requests; approvals present for all grants.'),
    ('00000000-0000-4000-a000-000000000402', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000104', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'MFA enforcement confirmed via Okta admin console screenshots included in the policy appendix.'),
    ('00000000-0000-4000-a000-000000000403', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000106', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Dashboards confirmed to cover all production services; alerting thresholds reviewed.'),
    ('00000000-0000-4000-a000-000000000404', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000107', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Playbook reviewed end-to-end; matches the actual incident handled in Q4 2025.'),
    ('00000000-0000-4000-a000-000000000405', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000109', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Uptime figures cross-checked against the public status page history.'),
    ('00000000-0000-4000-a000-000000000406', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000111', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Classification tiers reviewed; align with the data handled by each system.');

-- -----------------------------------------------------------------------------
-- 5. Audit events for the flow above.
-- -----------------------------------------------------------------------------

INSERT INTO audit_events (organization_id, actor_user_id, event_type,
                          entity_type, entity_id, metadata) VALUES
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'USER_CREATED', 'user', '00000000-0000-4000-a000-000000000010', '{"seed":true}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'USER_CREATED', 'user', '00000000-0000-4000-a000-000000000011', '{"seed":true,"role":"REVIEWER"}'),

    -- Evidence created (one per artifact seeded in section 2)
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000100', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000101', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000102', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000103', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000104', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000105', '{"seed":true,"source":"AWS"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000106', '{"seed":true,"source":"AWS"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000107', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000108', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000109', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000110', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000111', '{"seed":true,"source":"MANUAL_UPLOAD"}'),

    -- AI analyses (evidence that originated as an AI-suggested mapping)
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence', '00000000-0000-4000-a000-000000000101',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence', '00000000-0000-4000-a000-000000000102',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence', '00000000-0000-4000-a000-000000000105',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence', '00000000-0000-4000-a000-000000000108',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence', '00000000-0000-4000-a000-000000000110',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}'),

    -- Mappings created (one per row in section 3)
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000300', '{"seed":true,"controlCode":"CC6.3","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000303', '{"seed":true,"controlCode":"CC6.2","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000304', '{"seed":true,"controlCode":"CC6.6","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000305', '{"seed":true,"controlCode":"CC6.7","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000306', '{"seed":true,"controlCode":"CC7.1","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000307', '{"seed":true,"controlCode":"CC7.2","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000308', '{"seed":true,"controlCode":"CC9.1","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000309', '{"seed":true,"controlCode":"A1.1","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000311', '{"seed":true,"controlCode":"C1.1","type":"HUMAN_CONFIRMED"}'),

    -- Reviews recorded (one per row in section 4, skipping EV-100 already above)
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000100', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000103', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000104', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000106', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000107', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000109', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000111', '{"seed":true,"decision":"APPROVED"}');

-- -----------------------------------------------------------------------------
-- 6. Historical coverage-trend snapshots (past 14 days, NOT today).
--
--    The app's own CoverageSnapshotSweep records TODAY's real, live-computed
--    status at every backend boot — seeding a "today" row here would create
--    a duplicate that conflicts with the (org, control, day) unique
--    constraint. Instead this backfills the 14 days *before* today with an
--    honest ratchet-up trend: each control is treated as MISSING until the
--    day it first reached the final status the mappings above produce (e.g.
--    CC6.3 reaches COVERED 3 days ago, matching evidence 100's own
--    collected/approved date). Restart the backend after loading this seed
--    so it snapshots today's matching real state and the trend is unbroken.
-- -----------------------------------------------------------------------------

WITH org AS (SELECT '00000000-0000-4000-a000-000000000001'::uuid AS id),
     days AS (SELECT generate_series(1, 14) AS days_ago),
     control_trend AS (
       SELECT * FROM (VALUES
         ('CC6.1', 'NEEDS_REVIEW', 10),
         ('CC6.2', 'COVERED',      12),
         ('CC6.3', 'COVERED',       3),
         ('CC6.6', 'COVERED',       9),
         ('CC6.7', 'PARTIAL',       5),
         ('CC7.1', 'COVERED',       6),
         ('CC7.2', 'COVERED',       8),
         ('CC8.1', 'NEEDS_REVIEW',  1),
         ('CC9.1', 'PARTIAL',       4),
         ('CC9.2', 'MISSING',       0),
         ('A1.1',  'COVERED',      11),
         ('A1.2',  'NEEDS_REVIEW',  3),
         ('C1.1',  'COVERED',      13)
       ) AS t(code, final_status, days_to_reach)
     )
INSERT INTO control_status_snapshots (organization_id, control_id, status, snapshot_date)
SELECT org.id, ctl.id,
       CASE WHEN days.days_ago <= ct.days_to_reach THEN ct.final_status ELSE 'MISSING' END,
       (CURRENT_DATE - days.days_ago)
FROM org, days
JOIN control_trend ct ON true
JOIN controls ctl ON ctl.code = ct.code;

-- -----------------------------------------------------------------------------
-- 7. Bulk supplementary data for Demo Corp — evidence backlog, integrations,
--    collection history, and audit log volume, so every page that lists rows
--    has enough of them to exercise pagination and looks like a tenant that
--    has actually been running for a few months, not a hand-crafted fixture.
-- -----------------------------------------------------------------------------

-- 7a. ~48 bulk evidence artifacts. Most are left unmapped (a realistic
--     backlog); a few are AI-suggested against controls that are already
--     COVERED/PARTIAL/NEEDS_REVIEW (never the 3 genuinely-missing ones, so
--     the tuned 7/2/3/3 coverage story above is untouched); some are expired
--     or expiring soon so Review Queue shows all four reason types.
CREATE TEMP TABLE tmp_bulk_evidence (
    id            UUID        NOT NULL,
    name          TEXT        NOT NULL,
    source_type   TEXT        NOT NULL,
    source_system TEXT        NOT NULL,
    status        TEXT        NOT NULL,
    collected_at  TIMESTAMPTZ NOT NULL,
    expires_at    TIMESTAMPTZ,
    control_code  TEXT,
    size_bytes    BIGINT      NOT NULL,
    mime_type     TEXT        NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_bulk_evidence
SELECT
    gen_random_uuid(),
    (ARRAY['Vendor Security Questionnaire', 'Penetration Test Summary', 'SOC 2 Bridge Letter',
           'Firewall Rule Export', 'Employee Onboarding Checklist', 'Vulnerability Scan Report',
           'Data Retention Policy', 'Access Log Export', 'Change Ticket Export', 'Backup Job Log',
           'TLS Certificate Inventory', 'Password Policy Screenshot', 'Security Awareness Training Log',
           'Vendor Risk Assessment', 'Network Diagram Export'
          ])[1 + (gs % 15)] || ' - batch ' || gs,
    (ARRAY['MANUAL_UPLOAD', 'AWS', 'GITHUB', 'JIRA', 'GOOGLE_WORKSPACE'])[1 + (gs % 5)],
    (ARRAY['manual-upload', 'aws/prod-account', 'github/org-repo', 'jira/security-project', 'google/workspace-admin'])[1 + (gs % 5)],
    (ARRAY['COLLECTED', 'UNDER_REVIEW', 'APPROVED', 'EXPIRED', 'REJECTED'])[1 + (gs % 5)],
    NOW() - ((gs * 2) || ' days')::interval,
    CASE
        WHEN (ARRAY['COLLECTED', 'UNDER_REVIEW', 'APPROVED', 'EXPIRED', 'REJECTED'])[1 + (gs % 5)] = 'EXPIRED'
            THEN NOW() - ((1 + gs % 30) || ' days')::interval
        WHEN gs % 6 = 0 THEN NOW() + ((1 + gs % 6) || ' days')::interval
        ELSE NOW() + ((300 + gs) || ' days')::interval
    END,
    CASE WHEN gs % 4 = 0
        THEN (ARRAY['CC6.1', 'CC6.2', 'CC6.3', 'CC6.6', 'CC6.7', 'CC7.1', 'CC7.2', 'CC8.1', 'CC9.1', 'A1.1', 'A1.2', 'C1.1'])[1 + (gs % 12)]
        ELSE NULL
    END,
    512 + ((gs * 137) % 9000),
    (ARRAY['application/pdf', 'text/csv', 'application/json', 'image/png'])[1 + (gs % 4)]
FROM generate_series(1, 48) AS gs;

INSERT INTO evidence (id, organization_id, name, description, source_type, source_system,
                      status, collected_at, expires_at, created_by)
SELECT id, '00000000-0000-4000-a000-000000000001', name,
       'Additional supporting evidence collected during ongoing compliance operations.',
       source_type, source_system, status, collected_at, expires_at,
       '00000000-0000-4000-a000-000000000010'
FROM tmp_bulk_evidence;

INSERT INTO evidence_versions (id, evidence_id, organization_id, version, storage_key,
                               content_hash, size_bytes, mime_type, collector_version, collected_at)
SELECT gen_random_uuid(), id, '00000000-0000-4000-a000-000000000001', 1,
       'organizations/00000000-0000-4000-a000-000000000001/evidence/' || id || '/v1',
       'demo-seed-bulk-' || md5(id::text), size_bytes, mime_type, 'manual/1', collected_at
FROM tmp_bulk_evidence;

INSERT INTO evidence_control_mappings (id, organization_id, evidence_id, control_id,
                                       mapping_type, classification, confidence, reason)
SELECT gen_random_uuid(), '00000000-0000-4000-a000-000000000001', t.id, c.id, 'AI_SUGGESTED',
       (ARRAY['COVERED', 'PARTIAL', 'INSUFFICIENT'])[1 + (abs(hashtext(t.id::text)) % 3)],
       0.55 + (abs(hashtext(t.id::text)) % 40)::numeric / 100,
       'AI-suggested mapping pending human review.'
FROM tmp_bulk_evidence t
JOIN controls c ON c.code = t.control_code;

INSERT INTO audit_events (organization_id, actor_user_id, event_type, entity_type, entity_id, metadata, created_at)
SELECT '00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
       'EVIDENCE_CREATED', 'evidence', id, jsonb_build_object('seed', true, 'source', source_type), collected_at
FROM tmp_bulk_evidence;

-- 7b. Real ai_analysis rows matching the 5 "AI_ANALYSIS_CREATED" audit events
--     seeded in section 5 (those referenced evidence that never actually had an
--     ai_analysis row, so the Control Detail "AI analysis" panel was empty).
INSERT INTO ai_analysis (organization_id, evidence_id, control_id, provider, model,
                         prompt_version, classification, confidence, reason)
SELECT '00000000-0000-4000-a000-000000000001', e.evidence_id, c.id,
       'stub', 'stub-1', 'evidence-mapping/v1', e.classification, e.confidence, e.reason
FROM (VALUES
    ('00000000-0000-4000-a000-000000000101'::uuid, 'CC6.1', 'PARTIAL', 0.720,
     'Evidence lists current IAM users but does not demonstrate a periodic review or approval trail.'),
    ('00000000-0000-4000-a000-000000000102'::uuid, 'CC8.1', 'PARTIAL', 0.680,
     'Policy document exists but does not demonstrate that the peer-review process is consistently followed.'),
    ('00000000-0000-4000-a000-000000000105'::uuid, 'CC6.7', 'PARTIAL', 0.810,
     'Encryption-at-rest is clearly configured; in-transit settings for two internal services could not be confirmed.'),
    ('00000000-0000-4000-a000-000000000108'::uuid, 'CC9.1', 'PARTIAL', 0.760,
     'Risk register is present and current; treatment plans for two risks are still marked in-progress.'),
    ('00000000-0000-4000-a000-000000000110'::uuid, 'A1.2', 'PARTIAL', 0.650,
     'Restore test report is present but does not confirm the recovery time objective was met.')
) AS e(evidence_id, control_code, classification, confidence, reason)
JOIN controls c ON c.code = e.control_code;

-- 7c. Integrations + collection history.
INSERT INTO integrations (id, organization_id, provider, status, display_name, schedule,
                          last_tested_at, last_collection_at, created_by, created_at) VALUES
    ('00000000-0000-4000-a000-000000000500', '00000000-0000-4000-a000-000000000001',
     'GITHUB', 'CONNECTED', 'GitHub - demo-corp/platform', 'DAILY',
     NOW() - INTERVAL '1 days', NOW() - INTERVAL '6 hours', '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '90 days'),
    ('00000000-0000-4000-a000-000000000501', '00000000-0000-4000-a000-000000000001',
     'AWS', 'CONNECTED', 'AWS - prod account', 'DAILY',
     NOW() - INTERVAL '2 days', NOW() - INTERVAL '20 hours', '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '85 days'),
    ('00000000-0000-4000-a000-000000000502', '00000000-0000-4000-a000-000000000001',
     'JIRA', 'ERROR', 'Jira - Security project', 'WEEKLY',
     NOW() - INTERVAL '3 days', NOW() - INTERVAL '9 days', '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '70 days'),
    ('00000000-0000-4000-a000-000000000503', '00000000-0000-4000-a000-000000000001',
     'GOOGLE_WORKSPACE', 'DISCONNECTED', 'Google Workspace - IT admin', 'MANUAL',
     NOW() - INTERVAL '30 days', NULL, '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '60 days');

CREATE TEMP TABLE tmp_runs (
    id             UUID        NOT NULL,
    integration_id UUID        NOT NULL,
    status         TEXT        NOT NULL,
    trig           TEXT        NOT NULL,
    started_at     TIMESTAMPTZ NOT NULL,
    completed_at   TIMESTAMPTZ NOT NULL,
    ok_count       INT         NOT NULL,
    failed_count   INT         NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_runs
SELECT
    gen_random_uuid(),
    (ARRAY['00000000-0000-4000-a000-000000000500', '00000000-0000-4000-a000-000000000501',
           '00000000-0000-4000-a000-000000000502', '00000000-0000-4000-a000-000000000503'])[1 + (gs % 4)]::uuid,
    CASE WHEN gs % 11 = 0 THEN 'FAILED' WHEN gs % 7 = 0 THEN 'PARTIAL' ELSE 'COMPLETED' END,
    CASE WHEN gs % 3 = 0 THEN 'MANUAL' ELSE 'SCHEDULED' END,
    NOW() - ((gs * 36) || ' hours')::interval,
    NOW() - ((gs * 36) || ' hours')::interval + ((2 + gs % 8) || ' minutes')::interval,
    3 + (gs % 5),
    CASE WHEN gs % 11 = 0 THEN 1 + (gs % 3) WHEN gs % 7 = 0 THEN 1 ELSE 0 END
FROM generate_series(1, 48) AS gs;

INSERT INTO collection_runs (id, organization_id, integration_id, status, trigger, started_at,
                            completed_at, error_message, triggered_by, created_at)
SELECT id, '00000000-0000-4000-a000-000000000001', integration_id, status, trig, started_at,
       CASE WHEN status = 'FAILED' THEN NULL ELSE completed_at END,
       CASE WHEN status = 'FAILED' THEN 'Timed out contacting provider API.'
            WHEN status = 'PARTIAL' THEN 'Some items could not be collected.' ELSE NULL END,
       '00000000-0000-4000-a000-000000000010', started_at
FROM tmp_runs;

INSERT INTO collection_items (id, organization_id, run_id, evidence_type, status, message, created_at)
SELECT gen_random_uuid(), '00000000-0000-4000-a000-000000000001', r.id,
       (ARRAY['ACCESS_LOG', 'CONFIG_SNAPSHOT', 'REPO_BRANCH_PROTECTION', 'IAM_POLICY', 'TICKET_EXPORT'])[1 + ((r.ok_count + i) % 5)],
       CASE WHEN i <= r.ok_count THEN 'SUCCESS' ELSE 'FAILED' END,
       CASE WHEN i <= r.ok_count THEN 'Collected successfully.' ELSE 'Timed out contacting provider API.' END,
       r.started_at
FROM tmp_runs r
CROSS JOIN generate_series(1, 5) AS i
WHERE i <= (r.ok_count + r.failed_count);

-- 7d. Export jobs (Audit Package page history).
INSERT INTO export_jobs (organization_id, status, storage_key, size_bytes, triggered_by, started_at, completed_at, created_at) VALUES
    ('00000000-0000-4000-a000-000000000001', 'COMPLETED',
     'organizations/00000000-0000-4000-a000-000000000001/exports/audit-package-1.zip', 4_718_592,
     '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '45 days', NOW() - INTERVAL '45 days' + INTERVAL '90 seconds', NOW() - INTERVAL '45 days'),
    ('00000000-0000-4000-a000-000000000001', 'COMPLETED',
     'organizations/00000000-0000-4000-a000-000000000001/exports/audit-package-2.zip', 5_242_880,
     '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days' + INTERVAL '75 seconds', NOW() - INTERVAL '20 days'),
    ('00000000-0000-4000-a000-000000000001', 'COMPLETED',
     'organizations/00000000-0000-4000-a000-000000000001/exports/audit-package-3.zip', 5_509_120,
     '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days' + INTERVAL '82 seconds', NOW() - INTERVAL '2 days'),
    ('00000000-0000-4000-a000-000000000001', 'FAILED', NULL, NULL,
     '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '60 days', NOW() - INTERVAL '60 days' + INTERVAL '30 seconds', NOW() - INTERVAL '60 days');

-- 7e. Bulk audit-log noise spanning the past ~90 days (logins, mapping
--     decisions, integration events) so the Audit Log page has real depth.
INSERT INTO audit_events (organization_id, actor_user_id, event_type, entity_type, entity_id, metadata, created_at)
SELECT
    '00000000-0000-4000-a000-000000000001',
    (ARRAY['00000000-0000-4000-a000-000000000010', '00000000-0000-4000-a000-000000000011'])[1 + (gs % 2)]::uuid,
    (ARRAY['LOGIN', 'LOGOUT', 'EVIDENCE_REVIEWED', 'MAPPING_CONFIRMED', 'MAPPING_REJECTED',
           'INTEGRATION_TESTED', 'COLLECTION_COMPLETED', 'COLLECTION_FAILED'
          ])[1 + (gs % 8)],
    NULL, NULL,
    jsonb_build_object('seed', true, 'batch', 'noise'),
    NOW() - ((gs * 11) || ' hours')::interval
FROM generate_series(1, 140) AS gs;

-- -----------------------------------------------------------------------------
-- 8. Bulk fake customer organizations for the platform admin console — enough
--    rows to exercise pagination on both the organization table (10/page) and
--    the renewal-request queue (5/page), with a realistic spread of plans and
--    statuses (including a few expiring-soon and past-due/suspended/canceled).
-- -----------------------------------------------------------------------------

CREATE TEMP TABLE tmp_new_orgs (
    org_id        UUID        NOT NULL,
    org_name      TEXT        NOT NULL,
    org_slug      TEXT        NOT NULL,
    owner_user_id UUID        NOT NULL,
    owner_email   TEXT        NOT NULL,
    owner_name    TEXT        NOT NULL,
    plan          TEXT        NOT NULL,
    status        TEXT        NOT NULL,
    seat_limit    INT,
    trial_ends_at TIMESTAMPTZ,
    period_end    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL,
    req_plan      TEXT,
    req_seats     INT,
    req_note      TEXT
) ON COMMIT DROP;

INSERT INTO tmp_new_orgs
SELECT gen_random_uuid(), v.org_name, 'demo-cust-' || v.slug, gen_random_uuid(),
       v.owner_email, v.owner_name, v.plan, v.status, v.seat_limit,
       v.trial_ends_at, v.period_end, v.created_at, v.req_plan, v.req_seats, v.req_note
FROM (VALUES
    ('Nimbus Health', 'nimbus-health', 'owner@democustomer.example', 'Priya Natarajan',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '3 days', NULL::timestamptz, NOW() - INTERVAL '4 days',
     'STARTER', 10, 'Loved the trial, ready to convert to a paid plan.'),
    ('Foundry Robotics', 'foundry-robotics', 'owner2@democustomer.example', 'Diego Alvarez',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '6 days', NULL::timestamptz, NOW() - INTERVAL '8 days',
     NULL, NULL, NULL),
    ('Lattice Analytics', 'lattice-analytics', 'owner3@democustomer.example', 'Hannah Cho',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '13 days', NULL::timestamptz, NOW() - INTERVAL '1 days',
     NULL, NULL, NULL),
    ('Northwind Logistics', 'northwind-logistics', 'owner4@democustomer.example', 'Marcus Webb',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '9 days', NULL::timestamptz, NOW() - INTERVAL '5 days',
     'PRO', 25, 'We need SOC 2 done before our enterprise deal closes next month.'),
    ('BrightPath EdTech', 'brightpath-edtech', 'owner5@democustomer.example', 'Sara Lindqvist',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '21 days', NULL::timestamptz, NOW() - INTERVAL '2 days',
     NULL, NULL, NULL),
    ('Cascade FinTech', 'cascade-fintech', 'owner6@democustomer.example', 'Owen Baptiste',
     'STARTER', 'ACTIVE', 10, NULL::timestamptz, NOW() + INTERVAL '25 days', NOW() - INTERVAL '60 days',
     NULL, NULL, NULL),
    ('Solace Insurance', 'solace-insurance', 'owner7@democustomer.example', 'Renee Fischer',
     'STARTER', 'ACTIVE', 10, NULL::timestamptz, NOW() + INTERVAL '5 days', NOW() - INTERVAL '95 days',
     'PRO', 20, 'Adding two more compliance analysts, need more seats.'),
    ('Vertex Biotech', 'vertex-biotech', 'owner8@democustomer.example', 'Andre Kimura',
     'PRO', 'ACTIVE', 25, NULL::timestamptz, NOW() + INTERVAL '40 days', NOW() - INTERVAL '140 days',
     NULL, NULL, NULL),
    ('Anchor Legal Ops', 'anchor-legal-ops', 'owner9@democustomer.example', 'Felicia Grant',
     'PRO', 'ACTIVE', 25, NULL::timestamptz, NOW() + INTERVAL '18 days', NOW() - INTERVAL '75 days',
     'ENTERPRISE', 60, 'Board wants a dedicated support contact before we expand usage.'),
    ('Pinecone Retail', 'pinecone-retail', 'owner10@democustomer.example', 'Tomasz Nowak',
     'ENTERPRISE', 'ACTIVE', 100, NULL::timestamptz, NOW() + INTERVAL '55 days', NOW() - INTERVAL '210 days',
     NULL, NULL, NULL),
    ('Glacier Media', 'glacier-media', 'owner11@democustomer.example', 'Chidi Okafor',
     'PRO', 'PAST_DUE', 25, NULL::timestamptz, NOW() - INTERVAL '4 days', NOW() - INTERVAL '130 days',
     NULL, NULL, NULL),
    ('Ember Robotics Labs', 'ember-robotics-labs', 'owner12@democustomer.example', 'Ingrid Solberg',
     'STARTER', 'SUSPENDED', 10, NULL::timestamptz, NOW() - INTERVAL '20 days', NOW() - INTERVAL '150 days',
     NULL, NULL, NULL),
    ('Tidal Compliance Co', 'tidal-compliance-co', 'owner13@democustomer.example', 'Beatriz Souza',
     'ENTERPRISE', 'CANCELED', 60, NULL::timestamptz, NOW() - INTERVAL '35 days', NOW() - INTERVAL '260 days',
     NULL, NULL, NULL),
    ('Wavelength Security', 'wavelength-security', 'owner14@democustomer.example', 'Jonas Petrov',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '2 days', NULL::timestamptz, NOW() - INTERVAL '10 days',
     'STARTER', 8, 'Small team, just want to lock in a plan before the trial ends.')
) AS v(org_name, slug, owner_email, owner_name, plan, status, seat_limit,
       trial_ends_at, period_end, created_at, req_plan, req_seats, req_note);

INSERT INTO organizations (id, name, slug, onboarding_completed, onboarding_completed_at, created_at, updated_at)
SELECT org_id, org_name, org_slug, TRUE, created_at, created_at, created_at FROM tmp_new_orgs;

INSERT INTO users (id, email, password_hash, name)
SELECT owner_user_id, owner_email,
       '$2a$12$Lz86VSKdF6K7P4qd3LuQbOWudQKOsr6skAS5k2kExB4x3z8hdME6C', owner_name
FROM tmp_new_orgs;

INSERT INTO organization_members (organization_id, user_id, role)
SELECT org_id, owner_user_id, 'OWNER' FROM tmp_new_orgs;

INSERT INTO subscriptions (organization_id, plan, status, seat_limit, trial_ends_at, current_period_end)
SELECT org_id, plan, status, seat_limit, trial_ends_at, period_end FROM tmp_new_orgs;

INSERT INTO subscription_requests (organization_id, requested_by, requested_plan, requested_seat_limit, note)
SELECT org_id, owner_user_id, req_plan, req_seats, req_note
FROM tmp_new_orgs
WHERE req_plan IS NOT NULL;

-- A couple of already-reviewed requests (approved/rejected) for historical realism.
INSERT INTO subscription_requests (organization_id, requested_by, requested_plan, requested_seat_limit,
                                   note, status, reviewed_by, reviewed_at, review_note)
SELECT org_id, owner_user_id, 'PRO', 15, 'Ready to upgrade off our starter plan.',
       'APPROVED', '00000000-0000-4000-a000-000000000010'::uuid, NOW() - INTERVAL '30 days', NULL
FROM tmp_new_orgs WHERE org_name = 'Cascade FinTech'
UNION ALL
SELECT org_id, owner_user_id, 'ENTERPRISE', 40, 'Want enterprise features while past due.',
       'REJECTED', '00000000-0000-4000-a000-000000000010'::uuid, NOW() - INTERVAL '10 days',
       'Please bring your account current before upgrading.'
FROM tmp_new_orgs WHERE org_name = 'Ember Robotics Labs';

-- -----------------------------------------------------------------------------
-- 9. Policies — 4 policies covering the realistic mix of states the Policies
--    feature needs to demo: each publish mirrors the document into the same
--    `evidence` table used everywhere else (sourceType='POLICY'), so control
--    mapping/coverage reuses the existing evidence machinery unchanged.
-- -----------------------------------------------------------------------------

-- 9a. The mirrored evidence document for each policy.
INSERT INTO evidence (id, organization_id, name, description, source_type,
                      source_system, status, collected_at, expires_at, created_by)
VALUES
    ('00000000-0000-4000-a000-000000001200', '00000000-0000-4000-a000-000000000001',
     'Access Control Policy', 'Defines least-privilege access provisioning, periodic access review, and MFA requirements for all production systems.',
     'POLICY', 'policy', 'APPROVED',
     NOW() - INTERVAL '20 days', NOW() + INTERVAL '345 days', '00000000-0000-4000-a000-000000000010'),
    ('00000000-0000-4000-a000-000000001201', '00000000-0000-4000-a000-000000000001',
     'Incident Response Policy', 'Defines detection, escalation, containment, and post-incident review steps for security incidents.',
     'POLICY', 'policy', 'UNDER_REVIEW',
     NOW() - INTERVAL '5 days', NOW() + INTERVAL '360 days', '00000000-0000-4000-a000-000000000010'),
    ('00000000-0000-4000-a000-000000001202', '00000000-0000-4000-a000-000000000001',
     'Information Security Policy', 'Top-level information security policy covering roles, responsibilities, and the overall security program.',
     'POLICY', 'policy', 'COLLECTED',
     NOW() - INTERVAL '1 days', NOW() + INTERVAL '364 days', '00000000-0000-4000-a000-000000000010'),
    ('00000000-0000-4000-a000-000000001203', '00000000-0000-4000-a000-000000000001',
     'Data Retention & Disposal Policy', 'Defines retention periods and secure disposal procedures for customer and business data. Superseded by the 2026 revision; retained for historical record.',
     'POLICY', 'policy', 'APPROVED',
     NOW() - INTERVAL '200 days', NOW() + INTERVAL '165 days', '00000000-0000-4000-a000-000000000010');

INSERT INTO evidence_versions (id, evidence_id, organization_id, version,
                               storage_key, content_hash, size_bytes,
                               mime_type, collector_version, collected_at)
VALUES
    ('00000000-0000-4000-a000-000000001210', '00000000-0000-4000-a000-000000001200',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000001200/00000000-0000-4000-a000-000000001210',
     'demo-seed-hash-1200000000000000000000000000000000000000000000000000000',
     1200, 'application/pdf', 'manual/1', NOW() - INTERVAL '20 days'),
    ('00000000-0000-4000-a000-000000001211', '00000000-0000-4000-a000-000000001201',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000001201/00000000-0000-4000-a000-000000001211',
     'demo-seed-hash-1201000000000000000000000000000000000000000000000000000',
     1024, 'application/pdf', 'manual/1', NOW() - INTERVAL '5 days'),
    ('00000000-0000-4000-a000-000000001212', '00000000-0000-4000-a000-000000001202',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000001202/00000000-0000-4000-a000-000000001212',
     'demo-seed-hash-1202000000000000000000000000000000000000000000000000000',
     1536, 'application/pdf', 'manual/1', NOW() - INTERVAL '1 days'),
    ('00000000-0000-4000-a000-000000001213', '00000000-0000-4000-a000-000000001203',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000001203/00000000-0000-4000-a000-000000001213',
     'demo-seed-hash-1203000000000000000000000000000000000000000000000000000',
     896, 'application/pdf', 'manual/1', NOW() - INTERVAL '200 days');

-- 9b. Control mappings — Access Control Policy manually mapped + confirmed (matches the
--     "Add control" flow); Incident Response Policy shows the auto-suggested-on-publish
--     flow with 2 of 4 suggestions confirmed and 2 still pending; Information Security
--     and the archived Data Retention policy are deliberately left unmapped.
INSERT INTO evidence_control_mappings (id, organization_id, evidence_id,
                                       control_id, mapping_type, classification,
                                       confidence, reason, created_by)
SELECT m.id, m.organization_id, m.evidence_id, c.id, m.mapping_type, m.classification,
       m.confidence, m.reason, m.created_by
FROM (VALUES
    ('00000000-0000-4000-a000-000000001230'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000001200'::uuid, 'CC1.1',
     'HUMAN_CONFIRMED', 'COVERED', NULL::numeric,
     'Manually mapped from policy detail.',
     '00000000-0000-4000-a000-000000000010'::uuid),
    ('00000000-0000-4000-a000-000000001231'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000001201'::uuid, 'CC5.3',
     'HUMAN_CONFIRMED', 'COVERED', NULL::numeric,
     'Suggested based on policy type \u2014 review and confirm.',
     '00000000-0000-4000-a000-000000000010'::uuid),
    ('00000000-0000-4000-a000-000000001232'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000001201'::uuid, 'CC7.3',
     'HUMAN_CONFIRMED', 'COVERED', NULL::numeric,
     'Suggested based on policy type \u2014 review and confirm.',
     '00000000-0000-4000-a000-000000000010'::uuid),
    ('00000000-0000-4000-a000-000000001233'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000001201'::uuid, 'CC7.4',
     'AI_SUGGESTED', 'COVERED', NULL::numeric,
     'Suggested based on policy type \u2014 review and confirm.',
     '00000000-0000-4000-a000-000000000010'::uuid),
    ('00000000-0000-4000-a000-000000001234'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000001201'::uuid, 'CC7.5',
     'AI_SUGGESTED', 'COVERED', NULL::numeric,
     'Suggested based on policy type \u2014 review and confirm.',
     '00000000-0000-4000-a000-000000000010'::uuid)
) AS m(id, organization_id, evidence_id, control_code, mapping_type, classification,
       confidence, reason, created_by)
JOIN controls c ON c.code = m.control_code;

-- 9c. The policies themselves, each pointing at its mirrored evidence above.
INSERT INTO policies (id, organization_id, title, category, description, status,
                      owner_user_id, next_review_date, evidence_id, current_version,
                      attestation_cycle, cycle_started_at, created_by)
VALUES
    ('00000000-0000-4000-a000-000000001220', '00000000-0000-4000-a000-000000000001',
     'Access Control Policy', 'Access Control',
     'Defines least-privilege access provisioning, periodic access review, and MFA requirements for all production systems.',
     'PUBLISHED', '00000000-0000-4000-a000-000000000010', (NOW() + INTERVAL '340 days')::date,
     '00000000-0000-4000-a000-000000001200', 1, 1, NOW() - INTERVAL '20 days',
     '00000000-0000-4000-a000-000000000010'),
    ('00000000-0000-4000-a000-000000001221', '00000000-0000-4000-a000-000000000001',
     'Incident Response Policy', 'Incident Response',
     'Defines detection, escalation, containment, and post-incident review steps for security incidents.',
     'PUBLISHED', '00000000-0000-4000-a000-000000000011', (NOW() + INTERVAL '300 days')::date,
     '00000000-0000-4000-a000-000000001201', 1, 1, NOW() - INTERVAL '5 days',
     '00000000-0000-4000-a000-000000000010'),
    ('00000000-0000-4000-a000-000000001222', '00000000-0000-4000-a000-000000000001',
     'Information Security Policy', 'Information Security',
     'Top-level information security policy covering roles, responsibilities, and the overall security program.',
     'PUBLISHED', NULL, NULL,
     '00000000-0000-4000-a000-000000001202', 1, 1, NOW() - INTERVAL '1 days',
     '00000000-0000-4000-a000-000000000010'),
    ('00000000-0000-4000-a000-000000001223', '00000000-0000-4000-a000-000000000001',
     'Data Retention & Disposal Policy', 'Data Retention & Disposal',
     'Defines retention periods and secure disposal procedures for customer and business data. Superseded by the 2026 revision; retained for historical record.',
     'ARCHIVED', '00000000-0000-4000-a000-000000000010', (NOW() - INTERVAL '10 days')::date,
     '00000000-0000-4000-a000-000000001203', 1, 1, NOW() - INTERVAL '200 days',
     '00000000-0000-4000-a000-000000000010');

-- 9d. Acknowledgments — only the Access Control Policy (by the acknowledger, not yet by
--     owner/reviewer) and the archived Data Retention policy (fully acknowledged before
--     being superseded) have any; Incident Response and Information Security are
--     deliberately left with zero acknowledgments to show the pending state.
INSERT INTO policy_acknowledgments (id, organization_id, policy_id, policy_version,
                                    user_id, acknowledged_at, attestation_cycle)
VALUES
    ('00000000-0000-4000-a000-000000001240', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000001220', 1, '00000000-0000-4000-a000-000000000012',
     NOW() - INTERVAL '18 days', 1),
    ('00000000-0000-4000-a000-000000001241', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000001223', 1, '00000000-0000-4000-a000-000000000010',
     NOW() - INTERVAL '195 days', 1),
    ('00000000-0000-4000-a000-000000001242', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000001223', 1, '00000000-0000-4000-a000-000000000011',
     NOW() - INTERVAL '194 days', 1),
    ('00000000-0000-4000-a000-000000001243', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000001223', 1, '00000000-0000-4000-a000-000000000012',
     NOW() - INTERVAL '193 days', 1);

-- 9e. Audit trail for the policy lifecycle above.
INSERT INTO audit_events (organization_id, actor_user_id, event_type,
                          entity_type, entity_id, metadata) VALUES
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'USER_CREATED', 'user', '00000000-0000-4000-a000-000000000012', '{"seed":true,"role":"ACKNOWLEDGER"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'POLICY_CREATED', 'policy', '00000000-0000-4000-a000-000000001220', '{"seed":true,"title":"Access Control Policy"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'POLICY_CREATED', 'policy', '00000000-0000-4000-a000-000000001221', '{"seed":true,"title":"Incident Response Policy"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'POLICY_CREATED', 'policy', '00000000-0000-4000-a000-000000001222', '{"seed":true,"title":"Information Security Policy"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'POLICY_CREATED', 'policy', '00000000-0000-4000-a000-000000001223', '{"seed":true,"title":"Data Retention & Disposal Policy"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000012',
     'POLICY_ACKNOWLEDGED', 'policy', '00000000-0000-4000-a000-000000001220', '{"seed":true}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'POLICY_ARCHIVED', 'policy', '00000000-0000-4000-a000-000000001223', '{"seed":true}');

-- -----------------------------------------------------------------------------
-- 10. Control owners (v0.8.0) — 9 of 38 controls given a real owner. Deliberately
--     partial: CC9.2 (the MISSING vendor-risk control) is left unassigned so the
--     Readiness Report gap list still shows a real "Unassigned" row.
-- -----------------------------------------------------------------------------

INSERT INTO control_owners (id, organization_id, control_id, user_id)
SELECT o.id, o.organization_id, c.id, o.user_id
FROM (VALUES
    ('00000000-0000-4000-a000-000000001500'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC6.1', '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000001501'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC6.3', '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000001502'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC6.6', '00000000-0000-4000-a000-000000000010'::uuid),
    ('00000000-0000-4000-a000-000000001503'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC7.1', '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000001504'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC7.2', '00000000-0000-4000-a000-000000000010'::uuid),
    ('00000000-0000-4000-a000-000000001505'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC8.1', '00000000-0000-4000-a000-000000000010'::uuid),
    ('00000000-0000-4000-a000-000000001506'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC9.1', '00000000-0000-4000-a000-000000000010'::uuid),
    ('00000000-0000-4000-a000-000000001507'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'A1.1', '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000001508'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'C1.1', '00000000-0000-4000-a000-000000000010'::uuid)
) AS o(id, organization_id, control_code, user_id)
JOIN controls c ON c.code = o.control_code;

-- -----------------------------------------------------------------------------
-- 11. Risk register (v0.8.0) — 8 risks spanning every category, status, and score.
--     Most are deliberately linked to the same controls whose PARTIAL/NEEDS_REVIEW/
--     MISSING story above already implies a risk, so the register reads as the
--     cause behind gaps already visible elsewhere, not a disconnected list.
-- -----------------------------------------------------------------------------

INSERT INTO risks (id, organization_id, title, description, category, likelihood, impact,
                  status, owner_user_id, next_review_date)
VALUES
    ('00000000-0000-4000-a000-000000001600', '00000000-0000-4000-a000-000000000001',
     'Unencrypted data in transit between two internal services',
     'Two internal services still communicate over plain HTTP inside the VPC, identified during the CC6.7 evidence review. External traffic is unaffected.',
     'TECHNOLOGY', 'MEDIUM', 'HIGH', 'MITIGATING', '00000000-0000-4000-a000-000000000011',
     (NOW() + INTERVAL '30 days')::date),
    ('00000000-0000-4000-a000-000000001601', '00000000-0000-4000-a000-000000000001',
     'Quarterly access review lacks a consistent approval trail',
     'Access reviews happen but are not always accompanied by a signed-off approval record, so an auditor cannot always confirm who approved a retained grant.',
     'OPERATIONAL', 'MEDIUM', 'MEDIUM', 'MITIGATING', '00000000-0000-4000-a000-000000000010',
     (NOW() + INTERVAL '45 days')::date),
    ('00000000-0000-4000-a000-000000001602', '00000000-0000-4000-a000-000000000001',
     'Peer review not consistently enforced before production deploys',
     'Branch protection requires one approval, but a documented emergency-deploy path allows engineers to bypass it without a follow-up review being logged.',
     'OPERATIONAL', 'HIGH', 'MEDIUM', 'IDENTIFIED', NULL,
     (NOW() + INTERVAL '20 days')::date),
    ('00000000-0000-4000-a000-000000001603', '00000000-0000-4000-a000-000000000001',
     'Key subprocessor outage could disrupt service availability',
     'Demo Corp has no documented failover plan if its cloud hosting subprocessor has a regional outage. Accepted as a cost-of-doing-business risk for now given the subprocessor''s own SOC 2 Type II track record.',
     'THIRD_PARTY', 'LOW', 'HIGH', 'ACCEPTED', '00000000-0000-4000-a000-000000000010',
     (NOW() + INTERVAL '180 days')::date),
    ('00000000-0000-4000-a000-000000001604', '00000000-0000-4000-a000-000000000001',
     'No formal vendor risk classification process for new SaaS subprocessors',
     'New vendors are approved ad hoc by whoever signs up for the tool, with no consistent security review or risk tiering before customer data can reach them.',
     'THIRD_PARTY', 'MEDIUM', 'MEDIUM', 'IDENTIFIED', NULL,
     (NOW() + INTERVAL '30 days')::date),
    ('00000000-0000-4000-a000-000000001605', '00000000-0000-4000-a000-000000000001',
     'No segregation of duties between deploy approval and deploy execution',
     'The same engineer role can both approve and execute a production deploy. Mitigated by mandatory PR review plus deploy audit logging.',
     'FRAUD', 'LOW', 'HIGH', 'MITIGATED', '00000000-0000-4000-a000-000000000011',
     (NOW() + INTERVAL '90 days')::date),
    ('00000000-0000-4000-a000-000000001606', '00000000-0000-4000-a000-000000000001',
     'Key-person dependency on the legacy billing export script',
     'Only one engineer understands the legacy billing export process well enough to run it manually if the scheduled job fails. Not yet linked to a specific control — flagged for review with engineering leadership.',
     'OPERATIONAL', 'MEDIUM', 'MEDIUM', 'IDENTIFIED', NULL,
     (NOW() + INTERVAL '60 days')::date),
    ('00000000-0000-4000-a000-000000001607', '00000000-0000-4000-a000-000000000001',
     'Departing-employee offboarding is not consistently completed within 24 hours',
     'A sample of the last 5 departures showed account deactivation taking up to 4 business days, well past the documented same-day target.',
     'OPERATIONAL', 'HIGH', 'HIGH', 'IDENTIFIED', '00000000-0000-4000-a000-000000000010',
     (NOW() + INTERVAL '14 days')::date);

INSERT INTO risk_control_links (id, organization_id, risk_id, control_id)
SELECT l.id, l.organization_id, l.risk_id, c.id
FROM (VALUES
    ('00000000-0000-4000-a000-000000001700'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, '00000000-0000-4000-a000-000000001600'::uuid, 'CC6.7'),
    ('00000000-0000-4000-a000-000000001701'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, '00000000-0000-4000-a000-000000001601'::uuid, 'CC6.1'),
    ('00000000-0000-4000-a000-000000001702'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, '00000000-0000-4000-a000-000000001602'::uuid, 'CC8.1'),
    ('00000000-0000-4000-a000-000000001703'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, '00000000-0000-4000-a000-000000001603'::uuid, 'CC9.1'),
    ('00000000-0000-4000-a000-000000001704'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, '00000000-0000-4000-a000-000000001603'::uuid, 'A1.2'),
    ('00000000-0000-4000-a000-000000001705'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, '00000000-0000-4000-a000-000000001604'::uuid, 'CC9.2'),
    ('00000000-0000-4000-a000-000000001706'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, '00000000-0000-4000-a000-000000001605'::uuid, 'CC3.3'),
    ('00000000-0000-4000-a000-000000001707'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, '00000000-0000-4000-a000-000000001605'::uuid, 'CC8.1'),
    ('00000000-0000-4000-a000-000000001708'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, '00000000-0000-4000-a000-000000001607'::uuid, 'CC6.5')
    -- 00000000-...-001606 (key-person dependency) is intentionally left with NO
    -- linked control, to demonstrate the Readiness Report's "auditor gap" callout.
) AS l(id, organization_id, risk_id, control_code)
JOIN controls c ON c.code = l.control_code;

-- -----------------------------------------------------------------------------
-- 12. Control exceptions (v0.8.0) — 4 deviations within the 6-month observation
--     period: 3 remediated, 1 still open. Proves "evidence exists every month"
--     and "nothing went wrong" are different questions, even for controls that
--     are otherwise COVERED.
-- -----------------------------------------------------------------------------

INSERT INTO control_exceptions (id, organization_id, control_id, description,
                                detected_date, remediated_date, status, created_by)
SELECT e.id, e.organization_id, c.id, e.description, e.detected_date, e.remediated_date,
       e.status, e.created_by
FROM (VALUES
    ('00000000-0000-4000-a000-000000001800'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC6.3',
     'Quarterly access review for the billing service was completed 9 days after the scheduled deadline.',
     (NOW() - INTERVAL '4 months')::date, (NOW() - INTERVAL '4 months' + INTERVAL '9 days')::date,
     'REMEDIATED', '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000001801'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC7.2',
     'The Q2 incident-response tabletop exercise was rescheduled and completed 3 weeks later than planned.',
     (NOW() - INTERVAL '3 months')::date, (NOW() - INTERVAL '3 months' + INTERVAL '21 days')::date,
     'REMEDIATED', '00000000-0000-4000-a000-000000000010'::uuid),
    ('00000000-0000-4000-a000-000000001802'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC6.6',
     'One contractor account was found without MFA enabled during a spot-check; access was suspended and MFA enforced the same day.',
     (NOW() - INTERVAL '1 month')::date, (NOW() - INTERVAL '1 month')::date,
     'REMEDIATED', '00000000-0000-4000-a000-000000000010'::uuid),
    ('00000000-0000-4000-a000-000000001803'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC8.1',
     'A production hotfix was deployed via the emergency path without the standard peer-review approval during an active incident. Follow-up review not yet completed.',
     (NOW() - INTERVAL '20 days')::date, NULL,
     'OPEN', '00000000-0000-4000-a000-000000000011'::uuid)
) AS e(id, organization_id, control_code, description, detected_date, remediated_date, status, created_by)
JOIN controls c ON c.code = e.control_code;

-- -----------------------------------------------------------------------------
-- 13. Audit trail for sections 10-12 above.
-- -----------------------------------------------------------------------------

INSERT INTO audit_events (organization_id, actor_user_id, event_type,
                          entity_type, entity_id, metadata) VALUES
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'COMPLIANCE_PROGRAM_UPDATED', 'organization', '00000000-0000-4000-a000-000000000001', '{"seed":true,"reportType":"TYPE_II"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'CONTROL_OWNER_ASSIGNED', 'control_owner', '00000000-0000-4000-a000-000000001500', '{"seed":true,"controlCode":"CC6.1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'RISK_CREATED', 'risk', '00000000-0000-4000-a000-000000001607', '{"seed":true,"title":"Departing-employee offboarding is not consistently completed within 24 hours"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'CONTROL_EXCEPTION_LOGGED', 'control_exception', '00000000-0000-4000-a000-000000001803', '{"seed":true,"controlCode":"CC8.1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'CONTROL_EXCEPTION_REMEDIATED', 'control_exception', '00000000-0000-4000-a000-000000001802', '{"seed":true,"controlCode":"CC6.6"}');

-- -----------------------------------------------------------------------------
-- 14. Auditor/CPA firm collaboration data (v0.9.0) — the seeded demo-auditor
--     account (Karen Whitmore, Whitmore & Associates CPAs) has raised one open
--     evidence request, has one resolved review note, and has marked two
--     otherwise-COVERED controls as reviewed/tested — proving the Auditor
--     workspace and the org-side "Auditor requests" inbox both have real data
--     on first login instead of empty states.
-- -----------------------------------------------------------------------------

INSERT INTO auditor_requests (id, organization_id, control_id, type, message, status,
                              created_by, created_at, resolved_by, resolved_at, resolution_note)
SELECT r.id, r.organization_id, c.id, r.type, r.message, r.status,
       r.created_by, r.created_at, r.resolved_by, r.resolved_at, r.resolution_note
FROM (VALUES
    ('00000000-0000-4000-a000-000000001900'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC6.1',
     'EVIDENCE_REQUEST',
     'This IAM export is only AI-suggested so far. Can you confirm a human reviewed it, or attach the underlying access-review ticket?',
     'OPEN',
     '00000000-0000-4000-a000-000000000013'::uuid, NOW() - INTERVAL '5 days',
     NULL::uuid, NULL::timestamptz, NULL::text),
    ('00000000-0000-4000-a000-000000001901'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC8.1',
     'REVIEW_NOTE',
     'Noted the open exception on the emergency-hotfix deploy. Please confirm the follow-up peer review has a target completion date.',
     'RESOLVED',
     '00000000-0000-4000-a000-000000000013'::uuid, NOW() - INTERVAL '10 days',
     '00000000-0000-4000-a000-000000000010'::uuid, NOW() - INTERVAL '8 days',
     'Follow-up review scheduled for next sprint; tracked in the engineering backlog.')
) AS r(id, organization_id, control_code, type, message, status, created_by, created_at, resolved_by, resolved_at, resolution_note)
JOIN controls c ON c.code = r.control_code;

INSERT INTO auditor_control_reviews (id, organization_id, control_id, reviewed_by, reviewed_at, note)
SELECT v.id, v.organization_id, c.id, v.reviewed_by, v.reviewed_at, v.note
FROM (VALUES
    ('00000000-0000-4000-a000-000000001910'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC6.3',
     '00000000-0000-4000-a000-000000000013'::uuid, NOW() - INTERVAL '6 days',
     'Sampled the Q1 access review evidence; confirms the quarterly cadence is being followed.'),
    ('00000000-0000-4000-a000-000000001911'::uuid, '00000000-0000-4000-a000-000000000001'::uuid, 'CC9.1',
     '00000000-0000-4000-a000-000000000013'::uuid, NOW() - INTERVAL '2 days',
     'Reviewed vendor risk-assessment documentation; no follow-up needed.')
) AS v(id, organization_id, control_code, reviewed_by, reviewed_at, note)
JOIN controls c ON c.code = v.control_code;

INSERT INTO audit_events (organization_id, actor_user_id, event_type,
                          entity_type, entity_id, metadata) VALUES
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AUDITOR_INFO_UPDATED', 'organization', '00000000-0000-4000-a000-000000000001', '{"seed":true,"auditorFirmName":"Whitmore & Associates CPAs"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000013',
     'AUDITOR_REQUEST_CREATED', 'auditor_request', '00000000-0000-4000-a000-000000001900', '{"seed":true,"controlCode":"CC6.1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AUDITOR_REQUEST_RESOLVED', 'auditor_request', '00000000-0000-4000-a000-000000001901', '{"seed":true,"controlCode":"CC8.1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000013',
     'AUDITOR_CONTROL_REVIEWED', 'auditor_control_review', '00000000-0000-4000-a000-000000001910', '{"seed":true,"controlCode":"CC6.3"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000013',
     'AUDITOR_CONTROL_REVIEWED', 'auditor_control_review', '00000000-0000-4000-a000-000000001911', '{"seed":true,"controlCode":"CC9.1"}');

COMMIT;

-- =============================================================================
-- Verify from psql:
--   SELECT status, count(*)
--     FROM evidence
--    WHERE organization_id = '00000000-0000-4000-a000-000000000001'
--    GROUP BY status;
--
--   -- On the API/UI:
--   -- login as demo-owner@syncpoint.local / demo-password-2026
--   -- dashboard should show 7 COVERED, 2 PARTIAL, 3 NEEDS_REVIEW, 3 MISSING
--   -- (53% coverage)
--   -- Settings > Compliance Program should show Type II, a 6-month observation
--   -- period ending today, and all system-description fields filled in
--   -- /risk-register should show 8 risks; one (key-person dependency) with no
--   -- linked controls; one (offboarding) scored 9 and still IDENTIFIED
--   -- Readiness Report download should include a populated "EXCEPTIONS DURING
--   -- THE OBSERVATION PERIOD" section (3 remediated, 1 still open) and a
--   -- "TYPE II OBSERVATION PERIOD COVERAGE" section, plus an "AUDITOR ACTIVITY
--   -- DURING THE OBSERVATION PERIOD" section listing the 2 seeded review marks
--   -- login as demo-auditor@syncpoint.local / demo-password-2026 (role AUDITOR)
--   -- nav should show ONLY Overview/Controls/Risk Register/Policies/Exceptions
--   -- /auditor overview should show engagement info (Whitmore & Associates CPAs
--   -- is set on Settings > Auditor / CPA firm) and "Open requests: 1"
--   -- /auditor/controls/<CC6.1 id> should show the seeded open evidence request
--   -- /auditor/controls/<CC6.3 id> should show the seeded review mark
--   -- Settings > Auditor requests (as demo-owner) should show 1 open + 1 resolved
-- =============================================================================
