-- =============================================================================
-- Syncpoint Compliance — Demo Seed
--
-- Idempotent. Safe to run repeatedly against a running instance.
--
-- Produces a self-contained "Demo Corp" tenant covering all 15 SOC 2 demo
-- controls with a realistic mix of states:
--   * demo-owner@syncpoint.local     (password: demo-password-2026, role: OWNER, platform admin)
--   * demo-reviewer@syncpoint.local  (password: demo-password-2026, role: REVIEWER)
--   * 12 hand-authored evidence artifacts driving the exact coverage story below,
--     plus ~48 additional bulk evidence artifacts (mostly unmapped/backlog, some
--     expiring/expired, some AI-suggested) so Evidence/Review Queue have enough
--     rows to page through
--   * 7 controls COVERED (human-confirmed, approved evidence)
--   * 2 controls PARTIAL (human-confirmed, but only partial coverage)
--   * 3 controls NEEDS_REVIEW (AI-suggested, awaiting human confirmation)
--   * 3 controls MISSING (no evidence collected yet — realistic gaps)
--   * 14 days of coverage-trend history building up to that same result
--   * A PRO/ACTIVE subscription (25 seats) so the platform admin console
--     (visible to demo-owner) shows a paying customer, not just a bare trial
--   * 4 integrations (GitHub/AWS/Jira/Google Workspace) with ~48 historical
--     collection runs + items so the Activity page has real history
--   * ~200 audit events spanning the past ~90 days so the Audit Log has
--     enough rows to page through
--   * 14 additional fake customer organizations with varied plans/statuses
--     (including a few expiring-soon and past-due/suspended/canceled) plus
--     several subscription change requests, so the platform admin console's
--     organization table and renewal-request queue both have enough rows to
--     exercise pagination
--
-- Passwords are BCrypt-cost-12 hashes of the literal string above. They were
-- generated by the running backend and copied here so no bcrypt tooling is
-- required to install the seed.
--
-- Usage:
--   docker compose exec -T postgres psql -U compliance -d compliance \
--       < database/seed/demo.sql
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 0. Purge any existing demo state so the seed is fully idempotent.
-- -----------------------------------------------------------------------------

DELETE FROM organization_members
 WHERE user_id IN (
    SELECT id FROM users WHERE email IN
        ('demo-owner@syncpoint.local', 'demo-reviewer@syncpoint.local')
 );

DELETE FROM organizations WHERE slug LIKE 'demo-corp%';
DELETE FROM organizations WHERE slug LIKE 'reviewer-solo-org%';

-- Bulk fake customer organizations (section 8 below) + their owner accounts.
-- MUST run before deleting demo-owner: some of these orgs' historical
-- subscription_requests have demo-owner as reviewed_by (acting as platform
-- admin), and that foreign key has no ON DELETE action, so demo-owner can't
-- be deleted while it's still referenced.
DELETE FROM organizations WHERE slug LIKE 'demo-cust-%';
DELETE FROM users WHERE email LIKE '%@democustomer.example';

DELETE FROM users
 WHERE email IN ('demo-owner@syncpoint.local', 'demo-reviewer@syncpoint.local');

-- -----------------------------------------------------------------------------
-- 1. Core tenant entities. Fixed UUIDs keep the seed reproducible.
-- -----------------------------------------------------------------------------

INSERT INTO organizations (id, name, slug, onboarding_completed, onboarding_completed_at) VALUES
    ('00000000-0000-4000-a000-000000000001', 'Demo Corp', 'demo-corp', TRUE, NOW());

INSERT INTO users (id, email, password_hash, name, platform_admin) VALUES
    ('00000000-0000-4000-a000-000000000010',
     'demo-owner@syncpoint.local',
     '$2a$12$Lz86VSKdF6K7P4qd3LuQbOWudQKOsr6skAS5k2kExB4x3z8hdME6C',
     'Demo Owner', TRUE),
    ('00000000-0000-4000-a000-000000000011',
     'demo-reviewer@syncpoint.local',
     '$2a$12$NBZlfZ0TfiWsIVx1zb/D4.XdB.dtl5KSgjLxE9fp6otJs7kYTjbju',
     'Demo Reviewer', FALSE);

INSERT INTO organization_members (organization_id, user_id, role) VALUES
    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000010', 'OWNER'),
    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000011', 'REVIEWER');

-- Platform-admin console: give the demo tenant a real-looking paid subscription so the admin
-- console list isn't just a wall of fresh trials (V19's backfill row is cascade-deleted above
-- along with the org, so it must be re-seeded here every time this script runs).
INSERT INTO subscriptions (organization_id, plan, status, seat_limit, current_period_start, current_period_end) VALUES
    ('00000000-0000-4000-a000-000000000001', 'PRO', 'ACTIVE', 25, NOW() - INTERVAL '20 days', NOW() + INTERVAL '10 days');

-- A pending renewal/upgrade request so the platform admin's review queue isn't empty on a fresh seed.
INSERT INTO subscription_requests (organization_id, requested_by, requested_plan, requested_seat_limit, note) VALUES
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'ENTERPRISE', 50, 'Growing fast, need more seats and enterprise support.');


-- -----------------------------------------------------------------------------
-- 2. Sample evidence — one artifact per mapped control (12 of 15; CC8.2, CC9.2,
--    and P1.1 are deliberately left without evidence to demonstrate real gaps).
--
--    NOTE: evidence_versions rows point at storage_keys that will not exist
--    in MinIO because this SQL seed does not upload bytes. The application
--    tolerates this: analyze / download paths log a warning and continue.
--    Real bytes can be attached by uploading the same-named files via the UI.
-- -----------------------------------------------------------------------------

WITH org AS (SELECT '00000000-0000-4000-a000-000000000001'::uuid AS id),
     usr AS (SELECT '00000000-0000-4000-a000-000000000010'::uuid AS id)
INSERT INTO evidence (id, organization_id, name, description, source_type,
                      source_system, status, collected_at, expires_at, created_by)
SELECT * FROM (VALUES
    -- CC6.3 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000100'::uuid,
     (SELECT id FROM org),
     'Q1-2026 Access Review',
     'Quarterly review of production IAM access. Signed by the security lead.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '3 days',
     NOW() + INTERVAL '362 days',
     (SELECT id FROM usr)),
    -- CC6.1 — AI-suggested only, deliberately unconfirmed → NEEDS_REVIEW
    ('00000000-0000-4000-a000-000000000101'::uuid,
     (SELECT id FROM org),
     'AWS IAM User List (export)',
     'CSV export of production IAM users and their role assignments.',
     'MANUAL_UPLOAD', 'manual-upload',
     'COLLECTED',
     NOW() - INTERVAL '2 days',
     NOW() + INTERVAL '363 days',
     (SELECT id FROM usr)),
    -- CC8.1 — AI-suggested only → NEEDS_REVIEW
    ('00000000-0000-4000-a000-000000000102'::uuid,
     (SELECT id FROM org),
     'Change Management Policy',
     'Written policy on branch protection, code review, and deploy approvals.',
     'MANUAL_UPLOAD', 'manual-upload',
     'COLLECTED',
     NOW() - INTERVAL '1 days',
     NOW() + INTERVAL '364 days',
     (SELECT id FROM usr)),
    -- CC6.2 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000103'::uuid,
     (SELECT id FROM org),
     'Access Request & Approval Log - Q1 2026',
     'Ticketing export showing manager-approved access grants for the current quarter.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '12 days',
     NOW() + INTERVAL '353 days',
     (SELECT id FROM usr)),
    -- CC6.6 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000104'::uuid,
     (SELECT id FROM org),
     'Okta MFA Enforcement Policy',
     'Org-wide policy document showing MFA is required for all privileged and remote access.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '9 days',
     NOW() + INTERVAL '356 days',
     (SELECT id FROM usr)),
    -- CC6.7 — human-confirmed PARTIAL
    ('00000000-0000-4000-a000-000000000105'::uuid,
     (SELECT id FROM org),
     'Encryption Configuration Export',
     'Automated export of encryption-at-rest and in-transit settings across production data stores.',
     'AWS', 'aws/prod-account',
     'UNDER_REVIEW',
     NOW() - INTERVAL '5 days',
     NOW() + INTERVAL '360 days',
     (SELECT id FROM usr)),
    -- CC7.1 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000106'::uuid,
     (SELECT id FROM org),
     'CloudWatch Monitoring Dashboard Export',
     'Snapshot of production monitoring dashboards and alerting configuration.',
     'AWS', 'aws/prod-account',
     'APPROVED',
     NOW() - INTERVAL '6 days',
     NOW() + INTERVAL '359 days',
     (SELECT id FROM usr)),
    -- CC7.2 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000107'::uuid,
     (SELECT id FROM org),
     'Incident Response Playbook v3.2',
     'Documented incident response process covering detection, escalation, and post-incident review.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '8 days',
     NOW() + INTERVAL '357 days',
     (SELECT id FROM usr)),
    -- CC9.1 — human-confirmed PARTIAL
    ('00000000-0000-4000-a000-000000000108'::uuid,
     (SELECT id FROM org),
     'Annual Risk Assessment 2025',
     'Risk register identifying and scoring risks to the business and its systems.',
     'MANUAL_UPLOAD', 'manual-upload',
     'UNDER_REVIEW',
     NOW() - INTERVAL '4 days',
     NOW() + INTERVAL '361 days',
     (SELECT id FROM usr)),
    -- A1.1 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000109'::uuid,
     (SELECT id FROM org),
     'Uptime & Status Page Export - Q1 2026',
     'Historical uptime and incident data from the public status page.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '11 days',
     NOW() + INTERVAL '354 days',
     (SELECT id FROM usr)),
    -- A1.2 — AI-suggested only → NEEDS_REVIEW
    ('00000000-0000-4000-a000-000000000110'::uuid,
     (SELECT id FROM org),
     'Backup Restore Test Report - Q4 2025',
     'Report from the most recent disaster-recovery restore test.',
     'MANUAL_UPLOAD', 'manual-upload',
     'COLLECTED',
     NOW() - INTERVAL '3 days',
     NOW() + INTERVAL '362 days',
     (SELECT id FROM usr)),
    -- C1.1 — human-confirmed COVERED
    ('00000000-0000-4000-a000-000000000111'::uuid,
     (SELECT id FROM org),
     'Data Classification Policy v2',
     'Policy defining confidentiality tiers and required protections per tier.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '13 days',
     NOW() + INTERVAL '352 days',
     (SELECT id FROM usr))
) AS v(id, organization_id, name, description, source_type, source_system,
       status, collected_at, expires_at, created_by);

INSERT INTO evidence_versions (id, evidence_id, organization_id, version,
                               storage_key, content_hash, size_bytes,
                               mime_type, collector_version, collected_at)
VALUES
    ('00000000-0000-4000-a000-000000000200', '00000000-0000-4000-a000-000000000100',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000100/00000000-0000-4000-a000-000000000200',
     'demo-seed-hash-1000000000000000000000000000000000000000000000000000000',
     512, 'application/pdf', 'manual/1', NOW() - INTERVAL '3 days'),
    ('00000000-0000-4000-a000-000000000201', '00000000-0000-4000-a000-000000000101',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000101/00000000-0000-4000-a000-000000000201',
     'demo-seed-hash-1010000000000000000000000000000000000000000000000000000',
     2048, 'text/csv', 'manual/1', NOW() - INTERVAL '2 days'),
    ('00000000-0000-4000-a000-000000000202', '00000000-0000-4000-a000-000000000102',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000102/00000000-0000-4000-a000-000000000202',
     'demo-seed-hash-1020000000000000000000000000000000000000000000000000000',
     1024, 'application/pdf', 'manual/1', NOW() - INTERVAL '1 days'),
    ('00000000-0000-4000-a000-000000000203', '00000000-0000-4000-a000-000000000103',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000103/00000000-0000-4000-a000-000000000203',
     'demo-seed-hash-1030000000000000000000000000000000000000000000000000000',
     1536, 'application/pdf', 'manual/1', NOW() - INTERVAL '12 days'),
    ('00000000-0000-4000-a000-000000000204', '00000000-0000-4000-a000-000000000104',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000104/00000000-0000-4000-a000-000000000204',
     'demo-seed-hash-1040000000000000000000000000000000000000000000000000000',
     896, 'application/pdf', 'manual/1', NOW() - INTERVAL '9 days'),
    ('00000000-0000-4000-a000-000000000205', '00000000-0000-4000-a000-000000000105',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000105/00000000-0000-4000-a000-000000000205',
     'demo-seed-hash-1050000000000000000000000000000000000000000000000000000',
     4096, 'application/json', 'aws/1', NOW() - INTERVAL '5 days'),
    ('00000000-0000-4000-a000-000000000206', '00000000-0000-4000-a000-000000000106',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000106/00000000-0000-4000-a000-000000000206',
     'demo-seed-hash-1060000000000000000000000000000000000000000000000000000',
     5120, 'application/json', 'aws/1', NOW() - INTERVAL '6 days'),
    ('00000000-0000-4000-a000-000000000207', '00000000-0000-4000-a000-000000000107',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000107/00000000-0000-4000-a000-000000000207',
     'demo-seed-hash-1070000000000000000000000000000000000000000000000000000',
     8192, 'application/pdf', 'manual/1', NOW() - INTERVAL '8 days'),
    ('00000000-0000-4000-a000-000000000208', '00000000-0000-4000-a000-000000000108',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000108/00000000-0000-4000-a000-000000000208',
     'demo-seed-hash-1080000000000000000000000000000000000000000000000000000',
     2048, 'application/pdf', 'manual/1', NOW() - INTERVAL '4 days'),
    ('00000000-0000-4000-a000-000000000209', '00000000-0000-4000-a000-000000000109',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000109/00000000-0000-4000-a000-000000000209',
     'demo-seed-hash-1090000000000000000000000000000000000000000000000000000',
     1280, 'text/csv', 'manual/1', NOW() - INTERVAL '11 days'),
    ('00000000-0000-4000-a000-000000000210', '00000000-0000-4000-a000-000000000110',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000110/00000000-0000-4000-a000-000000000210',
     'demo-seed-hash-1100000000000000000000000000000000000000000000000000000',
     3584, 'application/pdf', 'manual/1', NOW() - INTERVAL '3 days'),
    ('00000000-0000-4000-a000-000000000211', '00000000-0000-4000-a000-000000000111',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000111/00000000-0000-4000-a000-000000000211',
     'demo-seed-hash-1110000000000000000000000000000000000000000000000000000',
     1024, 'application/pdf', 'manual/1', NOW() - INTERVAL '13 days');

-- -----------------------------------------------------------------------------
-- 3. Mappings — final tally across all 15 controls:
--      7 COVERED (CC6.2, CC6.3, CC6.6, CC7.1, CC7.2, A1.1, C1.1)
--      2 PARTIAL (CC6.7, CC9.1)
--      3 NEEDS_REVIEW (CC6.1, CC8.1, A1.2)
--      3 MISSING (CC8.2, CC9.2, P1.1 — no evidence collected yet)
-- -----------------------------------------------------------------------------

INSERT INTO evidence_control_mappings (id, organization_id, evidence_id,
                                       control_id, mapping_type, classification,
                                       confidence, reason, created_by)
SELECT m.id, m.organization_id, m.evidence_id, c.id, m.mapping_type, m.classification,
       m.confidence, m.reason, m.created_by
FROM (VALUES
    ('00000000-0000-4000-a000-000000000300'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000100'::uuid, 'CC6.3',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: signed quarterly access review is present.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000301'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000101'::uuid, 'CC6.1',
     'AI_SUGGESTED', 'PARTIAL', 0.720,
     'Evidence lists current IAM users but does not demonstrate a periodic review or approval trail.',
     NULL),
    ('00000000-0000-4000-a000-000000000302'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000102'::uuid, 'CC8.1',
     'AI_SUGGESTED', 'PARTIAL', 0.680,
     'Policy document exists but does not demonstrate that the peer-review process is consistently followed.',
     NULL),
    ('00000000-0000-4000-a000-000000000303'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000103'::uuid, 'CC6.2',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: every sampled access grant has a matching approval ticket.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000304'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000104'::uuid, 'CC6.6',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: MFA is enforced org-wide with no exceptions found.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000305'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000105'::uuid, 'CC6.7',
     'HUMAN_CONFIRMED', 'PARTIAL', 0.750,
     'Reviewer confirmed encryption-at-rest is enforced, but in-transit configuration for two internal services is still unverified.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000306'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000106'::uuid, 'CC7.1',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: dashboards and alerting cover all production services.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000307'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000107'::uuid, 'CC7.2',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: playbook covers detection through post-incident review.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000308'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000108'::uuid, 'CC9.1',
     'HUMAN_CONFIRMED', 'PARTIAL', 0.700,
     'Reviewer confirmed the risk register exists, but treatment plans for two identified risks are still in progress.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000309'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000109'::uuid, 'A1.1',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: uptime history matches the committed availability target.',
     '00000000-0000-4000-a000-000000000011'::uuid),
    ('00000000-0000-4000-a000-000000000310'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000110'::uuid, 'A1.2',
     'AI_SUGGESTED', 'PARTIAL', 0.650,
     'Restore test report is present but does not confirm the recovery time objective was met.',
     NULL),
    ('00000000-0000-4000-a000-000000000311'::uuid, '00000000-0000-4000-a000-000000000001'::uuid,
     '00000000-0000-4000-a000-000000000111'::uuid, 'C1.1',
     'HUMAN_CONFIRMED', 'COVERED', 1.000,
     'Reviewer confirmed: classification tiers and protections are clearly defined.',
     '00000000-0000-4000-a000-000000000011'::uuid)
) AS m(id, organization_id, evidence_id, control_code, mapping_type, classification,
       confidence, reason, created_by)
JOIN controls c ON c.code = m.control_code;

-- -----------------------------------------------------------------------------
-- 4. Reviews for every APPROVED evidence artifact above.
-- -----------------------------------------------------------------------------

INSERT INTO evidence_reviews (id, organization_id, evidence_id, reviewer_id,
                              decision, comments)
VALUES
    ('00000000-0000-4000-a000-000000000400', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000100', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Signed by security lead; scope and dates check out.'),
    ('00000000-0000-4000-a000-000000000401', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000103', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Ticket export matches sampled access requests; approvals present for all grants.'),
    ('00000000-0000-4000-a000-000000000402', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000104', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'MFA enforcement confirmed via Okta admin console screenshots included in the policy appendix.'),
    ('00000000-0000-4000-a000-000000000403', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000106', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Dashboards confirmed to cover all production services; alerting thresholds reviewed.'),
    ('00000000-0000-4000-a000-000000000404', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000107', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Playbook reviewed end-to-end; matches the actual incident handled in Q4 2025.'),
    ('00000000-0000-4000-a000-000000000405', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000109', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Uptime figures cross-checked against the public status page history.'),
    ('00000000-0000-4000-a000-000000000406', '00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000111', '00000000-0000-4000-a000-000000000011',
     'APPROVED', 'Classification tiers reviewed; align with the data handled by each system.');

-- -----------------------------------------------------------------------------
-- 5. Audit events for the flow above.
-- -----------------------------------------------------------------------------

INSERT INTO audit_events (organization_id, actor_user_id, event_type,
                          entity_type, entity_id, metadata) VALUES
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'USER_CREATED', 'user', '00000000-0000-4000-a000-000000000010', '{"seed":true}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'USER_CREATED', 'user', '00000000-0000-4000-a000-000000000011', '{"seed":true,"role":"REVIEWER"}'),

    -- Evidence created (one per artifact seeded in section 2)
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000100', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000101', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000102', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000103', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000104', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000105', '{"seed":true,"source":"AWS"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000106', '{"seed":true,"source":"AWS"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000107', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000108', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000109', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000110', '{"seed":true,"source":"MANUAL_UPLOAD"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence', '00000000-0000-4000-a000-000000000111', '{"seed":true,"source":"MANUAL_UPLOAD"}'),

    -- AI analyses (evidence that originated as an AI-suggested mapping)
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence', '00000000-0000-4000-a000-000000000101',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence', '00000000-0000-4000-a000-000000000102',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence', '00000000-0000-4000-a000-000000000105',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence', '00000000-0000-4000-a000-000000000108',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence', '00000000-0000-4000-a000-000000000110',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}'),

    -- Mappings created (one per row in section 3)
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000300', '{"seed":true,"controlCode":"CC6.3","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000303', '{"seed":true,"controlCode":"CC6.2","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000304', '{"seed":true,"controlCode":"CC6.6","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000305', '{"seed":true,"controlCode":"CC6.7","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000306', '{"seed":true,"controlCode":"CC7.1","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000307', '{"seed":true,"controlCode":"CC7.2","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000308', '{"seed":true,"controlCode":"CC9.1","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000309', '{"seed":true,"controlCode":"A1.1","type":"HUMAN_CONFIRMED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping', '00000000-0000-4000-a000-000000000311', '{"seed":true,"controlCode":"C1.1","type":"HUMAN_CONFIRMED"}'),

    -- Reviews recorded (one per row in section 4, skipping EV-100 already above)
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000100', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000103', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000104', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000106', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000107', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000109', '{"seed":true,"decision":"APPROVED"}'),
    ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence', '00000000-0000-4000-a000-000000000111', '{"seed":true,"decision":"APPROVED"}');

-- -----------------------------------------------------------------------------
-- 6. Historical coverage-trend snapshots (past 14 days, NOT today).
--
--    The app's own CoverageSnapshotSweep records TODAY's real, live-computed
--    status at every backend boot — seeding a "today" row here would create
--    a duplicate that conflicts with the (org, control, day) unique
--    constraint. Instead this backfills the 14 days *before* today with an
--    honest ratchet-up trend: each control is treated as MISSING until the
--    day it first reached the final status the mappings above produce (e.g.
--    CC6.3 reaches COVERED 3 days ago, matching evidence 100's own
--    collected/approved date). Restart the backend after loading this seed
--    so it snapshots today's matching real state and the trend is unbroken.
-- -----------------------------------------------------------------------------

WITH org AS (SELECT '00000000-0000-4000-a000-000000000001'::uuid AS id),
     days AS (SELECT generate_series(1, 14) AS days_ago),
     control_trend AS (
       SELECT * FROM (VALUES
         ('CC6.1', 'NEEDS_REVIEW', 10),
         ('CC6.2', 'COVERED',      12),
         ('CC6.3', 'COVERED',       3),
         ('CC6.6', 'COVERED',       9),
         ('CC6.7', 'PARTIAL',       5),
         ('CC7.1', 'COVERED',       6),
         ('CC7.2', 'COVERED',       8),
         ('CC8.1', 'NEEDS_REVIEW',  1),
         ('CC8.2', 'MISSING',       0),
         ('CC9.1', 'PARTIAL',       4),
         ('CC9.2', 'MISSING',       0),
         ('A1.1',  'COVERED',      11),
         ('A1.2',  'NEEDS_REVIEW',  3),
         ('C1.1',  'COVERED',      13),
         ('P1.1',  'MISSING',       0)
       ) AS t(code, final_status, days_to_reach)
     )
INSERT INTO control_status_snapshots (organization_id, control_id, status, snapshot_date)
SELECT org.id, ctl.id,
       CASE WHEN days.days_ago <= ct.days_to_reach THEN ct.final_status ELSE 'MISSING' END,
       (CURRENT_DATE - days.days_ago)
FROM org, days
JOIN control_trend ct ON true
JOIN controls ctl ON ctl.code = ct.code;

-- -----------------------------------------------------------------------------
-- 7. Bulk supplementary data for Demo Corp — evidence backlog, integrations,
--    collection history, and audit log volume, so every page that lists rows
--    has enough of them to exercise pagination and looks like a tenant that
--    has actually been running for a few months, not a hand-crafted fixture.
-- -----------------------------------------------------------------------------

-- 7a. ~48 bulk evidence artifacts. Most are left unmapped (a realistic
--     backlog); a few are AI-suggested against controls that are already
--     COVERED/PARTIAL/NEEDS_REVIEW (never the 3 genuinely-missing ones, so
--     the tuned 7/2/3/3 coverage story above is untouched); some are expired
--     or expiring soon so Review Queue shows all four reason types.
CREATE TEMP TABLE tmp_bulk_evidence (
    id            UUID        NOT NULL,
    name          TEXT        NOT NULL,
    source_type   TEXT        NOT NULL,
    source_system TEXT        NOT NULL,
    status        TEXT        NOT NULL,
    collected_at  TIMESTAMPTZ NOT NULL,
    expires_at    TIMESTAMPTZ,
    control_code  TEXT,
    size_bytes    BIGINT      NOT NULL,
    mime_type     TEXT        NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_bulk_evidence
SELECT
    gen_random_uuid(),
    (ARRAY['Vendor Security Questionnaire', 'Penetration Test Summary', 'SOC 2 Bridge Letter',
           'Firewall Rule Export', 'Employee Onboarding Checklist', 'Vulnerability Scan Report',
           'Data Retention Policy', 'Access Log Export', 'Change Ticket Export', 'Backup Job Log',
           'TLS Certificate Inventory', 'Password Policy Screenshot', 'Security Awareness Training Log',
           'Vendor Risk Assessment', 'Network Diagram Export'
          ])[1 + (gs % 15)] || ' - batch ' || gs,
    (ARRAY['MANUAL_UPLOAD', 'AWS', 'GITHUB', 'JIRA', 'GOOGLE_WORKSPACE'])[1 + (gs % 5)],
    (ARRAY['manual-upload', 'aws/prod-account', 'github/org-repo', 'jira/security-project', 'google/workspace-admin'])[1 + (gs % 5)],
    (ARRAY['COLLECTED', 'UNDER_REVIEW', 'APPROVED', 'EXPIRED', 'REJECTED'])[1 + (gs % 5)],
    NOW() - ((gs * 2) || ' days')::interval,
    CASE
        WHEN (ARRAY['COLLECTED', 'UNDER_REVIEW', 'APPROVED', 'EXPIRED', 'REJECTED'])[1 + (gs % 5)] = 'EXPIRED'
            THEN NOW() - ((1 + gs % 30) || ' days')::interval
        WHEN gs % 6 = 0 THEN NOW() + ((1 + gs % 6) || ' days')::interval
        ELSE NOW() + ((300 + gs) || ' days')::interval
    END,
    CASE WHEN gs % 4 = 0
        THEN (ARRAY['CC6.1', 'CC6.2', 'CC6.3', 'CC6.6', 'CC6.7', 'CC7.1', 'CC7.2', 'CC8.1', 'CC9.1', 'A1.1', 'A1.2', 'C1.1'])[1 + (gs % 12)]
        ELSE NULL
    END,
    512 + ((gs * 137) % 9000),
    (ARRAY['application/pdf', 'text/csv', 'application/json', 'image/png'])[1 + (gs % 4)]
FROM generate_series(1, 48) AS gs;

INSERT INTO evidence (id, organization_id, name, description, source_type, source_system,
                      status, collected_at, expires_at, created_by)
SELECT id, '00000000-0000-4000-a000-000000000001', name,
       'Additional supporting evidence collected during ongoing compliance operations.',
       source_type, source_system, status, collected_at, expires_at,
       '00000000-0000-4000-a000-000000000010'
FROM tmp_bulk_evidence;

INSERT INTO evidence_versions (id, evidence_id, organization_id, version, storage_key,
                               content_hash, size_bytes, mime_type, collector_version, collected_at)
SELECT gen_random_uuid(), id, '00000000-0000-4000-a000-000000000001', 1,
       'organizations/00000000-0000-4000-a000-000000000001/evidence/' || id || '/v1',
       'demo-seed-bulk-' || md5(id::text), size_bytes, mime_type, 'manual/1', collected_at
FROM tmp_bulk_evidence;

INSERT INTO evidence_control_mappings (id, organization_id, evidence_id, control_id,
                                       mapping_type, classification, confidence, reason)
SELECT gen_random_uuid(), '00000000-0000-4000-a000-000000000001', t.id, c.id, 'AI_SUGGESTED',
       (ARRAY['COVERED', 'PARTIAL', 'INSUFFICIENT'])[1 + (abs(hashtext(t.id::text)) % 3)],
       0.55 + (abs(hashtext(t.id::text)) % 40)::numeric / 100,
       'AI-suggested mapping pending human review.'
FROM tmp_bulk_evidence t
JOIN controls c ON c.code = t.control_code;

INSERT INTO audit_events (organization_id, actor_user_id, event_type, entity_type, entity_id, metadata, created_at)
SELECT '00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000010',
       'EVIDENCE_CREATED', 'evidence', id, jsonb_build_object('seed', true, 'source', source_type), collected_at
FROM tmp_bulk_evidence;

-- 7b. Real ai_analysis rows matching the 5 "AI_ANALYSIS_CREATED" audit events
--     seeded in section 5 (those referenced evidence that never actually had an
--     ai_analysis row, so the Control Detail "AI analysis" panel was empty).
INSERT INTO ai_analysis (organization_id, evidence_id, control_id, provider, model,
                         prompt_version, classification, confidence, reason)
SELECT '00000000-0000-4000-a000-000000000001', e.evidence_id, c.id,
       'stub', 'stub-1', 'evidence-mapping/v1', e.classification, e.confidence, e.reason
FROM (VALUES
    ('00000000-0000-4000-a000-000000000101'::uuid, 'CC6.1', 'PARTIAL', 0.720,
     'Evidence lists current IAM users but does not demonstrate a periodic review or approval trail.'),
    ('00000000-0000-4000-a000-000000000102'::uuid, 'CC8.1', 'PARTIAL', 0.680,
     'Policy document exists but does not demonstrate that the peer-review process is consistently followed.'),
    ('00000000-0000-4000-a000-000000000105'::uuid, 'CC6.7', 'PARTIAL', 0.810,
     'Encryption-at-rest is clearly configured; in-transit settings for two internal services could not be confirmed.'),
    ('00000000-0000-4000-a000-000000000108'::uuid, 'CC9.1', 'PARTIAL', 0.760,
     'Risk register is present and current; treatment plans for two risks are still marked in-progress.'),
    ('00000000-0000-4000-a000-000000000110'::uuid, 'A1.2', 'PARTIAL', 0.650,
     'Restore test report is present but does not confirm the recovery time objective was met.')
) AS e(evidence_id, control_code, classification, confidence, reason)
JOIN controls c ON c.code = e.control_code;

-- 7c. Integrations + collection history.
INSERT INTO integrations (id, organization_id, provider, status, display_name, schedule,
                          last_tested_at, last_collection_at, created_by, created_at) VALUES
    ('00000000-0000-4000-a000-000000000500', '00000000-0000-4000-a000-000000000001',
     'GITHUB', 'CONNECTED', 'GitHub - demo-corp/platform', 'DAILY',
     NOW() - INTERVAL '1 days', NOW() - INTERVAL '6 hours', '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '90 days'),
    ('00000000-0000-4000-a000-000000000501', '00000000-0000-4000-a000-000000000001',
     'AWS', 'CONNECTED', 'AWS - prod account', 'DAILY',
     NOW() - INTERVAL '2 days', NOW() - INTERVAL '20 hours', '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '85 days'),
    ('00000000-0000-4000-a000-000000000502', '00000000-0000-4000-a000-000000000001',
     'JIRA', 'ERROR', 'Jira - Security project', 'WEEKLY',
     NOW() - INTERVAL '3 days', NOW() - INTERVAL '9 days', '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '70 days'),
    ('00000000-0000-4000-a000-000000000503', '00000000-0000-4000-a000-000000000001',
     'GOOGLE_WORKSPACE', 'DISCONNECTED', 'Google Workspace - IT admin', 'MANUAL',
     NOW() - INTERVAL '30 days', NULL, '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '60 days');

CREATE TEMP TABLE tmp_runs (
    id             UUID        NOT NULL,
    integration_id UUID        NOT NULL,
    status         TEXT        NOT NULL,
    trig           TEXT        NOT NULL,
    started_at     TIMESTAMPTZ NOT NULL,
    completed_at   TIMESTAMPTZ NOT NULL,
    ok_count       INT         NOT NULL,
    failed_count   INT         NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_runs
SELECT
    gen_random_uuid(),
    (ARRAY['00000000-0000-4000-a000-000000000500', '00000000-0000-4000-a000-000000000501',
           '00000000-0000-4000-a000-000000000502', '00000000-0000-4000-a000-000000000503'])[1 + (gs % 4)]::uuid,
    CASE WHEN gs % 11 = 0 THEN 'FAILED' WHEN gs % 7 = 0 THEN 'PARTIAL' ELSE 'COMPLETED' END,
    CASE WHEN gs % 3 = 0 THEN 'MANUAL' ELSE 'SCHEDULED' END,
    NOW() - ((gs * 36) || ' hours')::interval,
    NOW() - ((gs * 36) || ' hours')::interval + ((2 + gs % 8) || ' minutes')::interval,
    3 + (gs % 5),
    CASE WHEN gs % 11 = 0 THEN 1 + (gs % 3) WHEN gs % 7 = 0 THEN 1 ELSE 0 END
FROM generate_series(1, 48) AS gs;

INSERT INTO collection_runs (id, organization_id, integration_id, status, trigger, started_at,
                            completed_at, error_message, triggered_by, created_at)
SELECT id, '00000000-0000-4000-a000-000000000001', integration_id, status, trig, started_at,
       CASE WHEN status = 'FAILED' THEN NULL ELSE completed_at END,
       CASE WHEN status = 'FAILED' THEN 'Timed out contacting provider API.'
            WHEN status = 'PARTIAL' THEN 'Some items could not be collected.' ELSE NULL END,
       '00000000-0000-4000-a000-000000000010', started_at
FROM tmp_runs;

INSERT INTO collection_items (id, organization_id, run_id, evidence_type, status, message, created_at)
SELECT gen_random_uuid(), '00000000-0000-4000-a000-000000000001', r.id,
       (ARRAY['ACCESS_LOG', 'CONFIG_SNAPSHOT', 'REPO_BRANCH_PROTECTION', 'IAM_POLICY', 'TICKET_EXPORT'])[1 + ((r.ok_count + i) % 5)],
       CASE WHEN i <= r.ok_count THEN 'SUCCESS' ELSE 'FAILED' END,
       CASE WHEN i <= r.ok_count THEN 'Collected successfully.' ELSE 'Timed out contacting provider API.' END,
       r.started_at
FROM tmp_runs r
CROSS JOIN generate_series(1, 5) AS i
WHERE i <= (r.ok_count + r.failed_count);

-- 7d. Export jobs (Audit Package page history).
INSERT INTO export_jobs (organization_id, status, storage_key, size_bytes, triggered_by, started_at, completed_at, created_at) VALUES
    ('00000000-0000-4000-a000-000000000001', 'COMPLETED',
     'organizations/00000000-0000-4000-a000-000000000001/exports/audit-package-1.zip', 4_718_592,
     '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '45 days', NOW() - INTERVAL '45 days' + INTERVAL '90 seconds', NOW() - INTERVAL '45 days'),
    ('00000000-0000-4000-a000-000000000001', 'COMPLETED',
     'organizations/00000000-0000-4000-a000-000000000001/exports/audit-package-2.zip', 5_242_880,
     '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days' + INTERVAL '75 seconds', NOW() - INTERVAL '20 days'),
    ('00000000-0000-4000-a000-000000000001', 'COMPLETED',
     'organizations/00000000-0000-4000-a000-000000000001/exports/audit-package-3.zip', 5_509_120,
     '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days' + INTERVAL '82 seconds', NOW() - INTERVAL '2 days'),
    ('00000000-0000-4000-a000-000000000001', 'FAILED', NULL, NULL,
     '00000000-0000-4000-a000-000000000010', NOW() - INTERVAL '60 days', NOW() - INTERVAL '60 days' + INTERVAL '30 seconds', NOW() - INTERVAL '60 days');

-- 7e. Bulk audit-log noise spanning the past ~90 days (logins, mapping
--     decisions, integration events) so the Audit Log page has real depth.
INSERT INTO audit_events (organization_id, actor_user_id, event_type, entity_type, entity_id, metadata, created_at)
SELECT
    '00000000-0000-4000-a000-000000000001',
    (ARRAY['00000000-0000-4000-a000-000000000010', '00000000-0000-4000-a000-000000000011'])[1 + (gs % 2)]::uuid,
    (ARRAY['LOGIN', 'LOGOUT', 'EVIDENCE_REVIEWED', 'MAPPING_CONFIRMED', 'MAPPING_REJECTED',
           'INTEGRATION_TESTED', 'COLLECTION_COMPLETED', 'COLLECTION_FAILED'
          ])[1 + (gs % 8)],
    NULL, NULL,
    jsonb_build_object('seed', true, 'batch', 'noise'),
    NOW() - ((gs * 11) || ' hours')::interval
FROM generate_series(1, 140) AS gs;

-- -----------------------------------------------------------------------------
-- 8. Bulk fake customer organizations for the platform admin console — enough
--    rows to exercise pagination on both the organization table (10/page) and
--    the renewal-request queue (5/page), with a realistic spread of plans and
--    statuses (including a few expiring-soon and past-due/suspended/canceled).
-- -----------------------------------------------------------------------------

CREATE TEMP TABLE tmp_new_orgs (
    org_id        UUID        NOT NULL,
    org_name      TEXT        NOT NULL,
    org_slug      TEXT        NOT NULL,
    owner_user_id UUID        NOT NULL,
    owner_email   TEXT        NOT NULL,
    owner_name    TEXT        NOT NULL,
    plan          TEXT        NOT NULL,
    status        TEXT        NOT NULL,
    seat_limit    INT,
    trial_ends_at TIMESTAMPTZ,
    period_end    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL,
    req_plan      TEXT,
    req_seats     INT,
    req_note      TEXT
) ON COMMIT DROP;

INSERT INTO tmp_new_orgs
SELECT gen_random_uuid(), v.org_name, 'demo-cust-' || v.slug, gen_random_uuid(),
       v.owner_email, v.owner_name, v.plan, v.status, v.seat_limit,
       v.trial_ends_at, v.period_end, v.created_at, v.req_plan, v.req_seats, v.req_note
FROM (VALUES
    ('Nimbus Health', 'nimbus-health', 'owner@democustomer.example', 'Priya Natarajan',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '3 days', NULL::timestamptz, NOW() - INTERVAL '4 days',
     'STARTER', 10, 'Loved the trial, ready to convert to a paid plan.'),
    ('Foundry Robotics', 'foundry-robotics', 'owner2@democustomer.example', 'Diego Alvarez',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '6 days', NULL::timestamptz, NOW() - INTERVAL '8 days',
     NULL, NULL, NULL),
    ('Lattice Analytics', 'lattice-analytics', 'owner3@democustomer.example', 'Hannah Cho',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '13 days', NULL::timestamptz, NOW() - INTERVAL '1 days',
     NULL, NULL, NULL),
    ('Northwind Logistics', 'northwind-logistics', 'owner4@democustomer.example', 'Marcus Webb',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '9 days', NULL::timestamptz, NOW() - INTERVAL '5 days',
     'PRO', 25, 'We need SOC 2 done before our enterprise deal closes next month.'),
    ('BrightPath EdTech', 'brightpath-edtech', 'owner5@democustomer.example', 'Sara Lindqvist',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '21 days', NULL::timestamptz, NOW() - INTERVAL '2 days',
     NULL, NULL, NULL),
    ('Cascade FinTech', 'cascade-fintech', 'owner6@democustomer.example', 'Owen Baptiste',
     'STARTER', 'ACTIVE', 10, NULL::timestamptz, NOW() + INTERVAL '25 days', NOW() - INTERVAL '60 days',
     NULL, NULL, NULL),
    ('Solace Insurance', 'solace-insurance', 'owner7@democustomer.example', 'Renee Fischer',
     'STARTER', 'ACTIVE', 10, NULL::timestamptz, NOW() + INTERVAL '5 days', NOW() - INTERVAL '95 days',
     'PRO', 20, 'Adding two more compliance analysts, need more seats.'),
    ('Vertex Biotech', 'vertex-biotech', 'owner8@democustomer.example', 'Andre Kimura',
     'PRO', 'ACTIVE', 25, NULL::timestamptz, NOW() + INTERVAL '40 days', NOW() - INTERVAL '140 days',
     NULL, NULL, NULL),
    ('Anchor Legal Ops', 'anchor-legal-ops', 'owner9@democustomer.example', 'Felicia Grant',
     'PRO', 'ACTIVE', 25, NULL::timestamptz, NOW() + INTERVAL '18 days', NOW() - INTERVAL '75 days',
     'ENTERPRISE', 60, 'Board wants a dedicated support contact before we expand usage.'),
    ('Pinecone Retail', 'pinecone-retail', 'owner10@democustomer.example', 'Tomasz Nowak',
     'ENTERPRISE', 'ACTIVE', 100, NULL::timestamptz, NOW() + INTERVAL '55 days', NOW() - INTERVAL '210 days',
     NULL, NULL, NULL),
    ('Glacier Media', 'glacier-media', 'owner11@democustomer.example', 'Chidi Okafor',
     'PRO', 'PAST_DUE', 25, NULL::timestamptz, NOW() - INTERVAL '4 days', NOW() - INTERVAL '130 days',
     NULL, NULL, NULL),
    ('Ember Robotics Labs', 'ember-robotics-labs', 'owner12@democustomer.example', 'Ingrid Solberg',
     'STARTER', 'SUSPENDED', 10, NULL::timestamptz, NOW() - INTERVAL '20 days', NOW() - INTERVAL '150 days',
     NULL, NULL, NULL),
    ('Tidal Compliance Co', 'tidal-compliance-co', 'owner13@democustomer.example', 'Beatriz Souza',
     'ENTERPRISE', 'CANCELED', 60, NULL::timestamptz, NOW() - INTERVAL '35 days', NOW() - INTERVAL '260 days',
     NULL, NULL, NULL),
    ('Wavelength Security', 'wavelength-security', 'owner14@democustomer.example', 'Jonas Petrov',
     'TRIAL', 'TRIALING', NULL::int, NOW() + INTERVAL '2 days', NULL::timestamptz, NOW() - INTERVAL '10 days',
     'STARTER', 8, 'Small team, just want to lock in a plan before the trial ends.')
) AS v(org_name, slug, owner_email, owner_name, plan, status, seat_limit,
       trial_ends_at, period_end, created_at, req_plan, req_seats, req_note);

INSERT INTO organizations (id, name, slug, onboarding_completed, onboarding_completed_at, created_at, updated_at)
SELECT org_id, org_name, org_slug, TRUE, created_at, created_at, created_at FROM tmp_new_orgs;

INSERT INTO users (id, email, password_hash, name)
SELECT owner_user_id, owner_email,
       '$2a$12$Lz86VSKdF6K7P4qd3LuQbOWudQKOsr6skAS5k2kExB4x3z8hdME6C', owner_name
FROM tmp_new_orgs;

INSERT INTO organization_members (organization_id, user_id, role)
SELECT org_id, owner_user_id, 'OWNER' FROM tmp_new_orgs;

INSERT INTO subscriptions (organization_id, plan, status, seat_limit, trial_ends_at, current_period_end)
SELECT org_id, plan, status, seat_limit, trial_ends_at, period_end FROM tmp_new_orgs;

INSERT INTO subscription_requests (organization_id, requested_by, requested_plan, requested_seat_limit, note)
SELECT org_id, owner_user_id, req_plan, req_seats, req_note
FROM tmp_new_orgs
WHERE req_plan IS NOT NULL;

-- A couple of already-reviewed requests (approved/rejected) for historical realism.
INSERT INTO subscription_requests (organization_id, requested_by, requested_plan, requested_seat_limit,
                                   note, status, reviewed_by, reviewed_at, review_note)
SELECT org_id, owner_user_id, 'PRO', 15, 'Ready to upgrade off our starter plan.',
       'APPROVED', '00000000-0000-4000-a000-000000000010'::uuid, NOW() - INTERVAL '30 days', NULL
FROM tmp_new_orgs WHERE org_name = 'Cascade FinTech'
UNION ALL
SELECT org_id, owner_user_id, 'ENTERPRISE', 40, 'Want enterprise features while past due.',
       'REJECTED', '00000000-0000-4000-a000-000000000010'::uuid, NOW() - INTERVAL '10 days',
       'Please bring your account current before upgrading.'
FROM tmp_new_orgs WHERE org_name = 'Ember Robotics Labs';

COMMIT;

-- =============================================================================
-- Verify from psql:
--   SELECT status, count(*)
--     FROM evidence
--    WHERE organization_id = '00000000-0000-4000-a000-000000000001'
--    GROUP BY status;
--
--   -- On the API/UI:
--   -- login as demo-owner@syncpoint.local / demo-password-2026
--   -- dashboard should show 7 COVERED, 2 PARTIAL, 3 NEEDS_REVIEW, 3 MISSING
--   -- (53% coverage)
-- =============================================================================
