-- =============================================================================
-- Syncpoint Compliance — Demo Seed
--
-- Idempotent. Safe to run repeatedly against a running instance.
--
-- Produces a self-contained "Demo Corp" tenant with:
--   * demo-owner@syncpoint.local     (password: demo-password-2026, role: OWNER)
--   * demo-reviewer@syncpoint.local  (password: demo-password-2026, role: REVIEWER)
--   * three evidence artifacts illustrating each product state
--   * one AI-suggested mapping (control shows NEEDS_REVIEW)
--   * one human-confirmed mapping + approval (control shows COVERED)
--   * one un-mapped evidence (nothing to show)
--
-- Passwords are BCrypt-cost-12 hashes of the literal string above. They were
-- generated by the running backend and copied here so no bcrypt tooling is
-- required to install the seed.
--
-- Usage:
--   docker compose exec -T postgres psql -U compliance -d compliance \
--       < database/seed/demo.sql
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 0. Purge any existing demo state so the seed is fully idempotent.
-- -----------------------------------------------------------------------------

DELETE FROM organization_members
 WHERE user_id IN (
    SELECT id FROM users WHERE email IN
        ('demo-owner@syncpoint.local', 'demo-reviewer@syncpoint.local')
 );

DELETE FROM organizations WHERE slug LIKE 'demo-corp%';
DELETE FROM organizations WHERE slug LIKE 'reviewer-solo-org%';
DELETE FROM users
 WHERE email IN ('demo-owner@syncpoint.local', 'demo-reviewer@syncpoint.local');

-- -----------------------------------------------------------------------------
-- 1. Core tenant entities. Fixed UUIDs keep the seed reproducible.
-- -----------------------------------------------------------------------------

INSERT INTO organizations (id, name, slug) VALUES
    ('00000000-0000-4000-a000-000000000001', 'Demo Corp', 'demo-corp');

INSERT INTO users (id, email, password_hash, name) VALUES
    ('00000000-0000-4000-a000-000000000010',
     'demo-owner@syncpoint.local',
     '$2a$12$Lz86VSKdF6K7P4qd3LuQbOWudQKOsr6skAS5k2kExB4x3z8hdME6C',
     'Demo Owner'),
    ('00000000-0000-4000-a000-000000000011',
     'demo-reviewer@syncpoint.local',
     '$2a$12$NBZlfZ0TfiWsIVx1zb/D4.XdB.dtl5KSgjLxE9fp6otJs7kYTjbju',
     'Demo Reviewer');

INSERT INTO organization_members (organization_id, user_id, role) VALUES
    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000010', 'OWNER'),
    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000011', 'REVIEWER');

-- -----------------------------------------------------------------------------
-- 2. Sample evidence.
--
--    NOTE: evidence_versions rows point at storage_keys that will not exist
--    in MinIO because this SQL seed does not upload bytes. The application
--    tolerates this: analyze / download paths log a warning and continue.
--    Real bytes can be attached by uploading the same-named files via the UI.
-- -----------------------------------------------------------------------------

WITH cc63 AS (SELECT id FROM controls WHERE code = 'CC6.3'),
     cc61 AS (SELECT id FROM controls WHERE code = 'CC6.1'),
     org  AS (SELECT '00000000-0000-4000-a000-000000000001'::uuid AS id),
     usr  AS (SELECT '00000000-0000-4000-a000-000000000010'::uuid AS id)
INSERT INTO evidence (id, organization_id, name, description, source_type,
                      source_system, status, collected_at, expires_at, created_by)
SELECT * FROM (VALUES
    ('00000000-0000-4000-a000-000000000100'::uuid,
     (SELECT id FROM org),
     'Q1-2026 Access Review',
     'Quarterly review of production IAM access. Signed by the security lead.',
     'MANUAL_UPLOAD', 'manual-upload',
     'APPROVED',
     NOW() - INTERVAL '3 days',
     NOW() + INTERVAL '362 days',
     (SELECT id FROM usr)),
    ('00000000-0000-4000-a000-000000000101'::uuid,
     (SELECT id FROM org),
     'AWS IAM User List (export)',
     'CSV export of production IAM users and their role assignments.',
     'MANUAL_UPLOAD', 'manual-upload',
     'COLLECTED',
     NOW() - INTERVAL '2 days',
     NOW() + INTERVAL '363 days',
     (SELECT id FROM usr)),
    ('00000000-0000-4000-a000-000000000102'::uuid,
     (SELECT id FROM org),
     'Change Management Policy',
     'Written policy on branch protection, code review, and deploy approvals.',
     'MANUAL_UPLOAD', 'manual-upload',
     'COLLECTED',
     NOW() - INTERVAL '1 days',
     NOW() + INTERVAL '364 days',
     (SELECT id FROM usr))
) AS v(id, organization_id, name, description, source_type, source_system,
       status, collected_at, expires_at, created_by);

INSERT INTO evidence_versions (id, evidence_id, organization_id, version,
                               storage_key, content_hash, size_bytes,
                               mime_type, collector_version, collected_at)
VALUES
    ('00000000-0000-4000-a000-000000000200',
     '00000000-0000-4000-a000-000000000100',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000100/00000000-0000-4000-a000-000000000200',
     'demo-seed-hash-1000000000000000000000000000000000000000000000000000000',
     512, 'application/pdf', 'manual/1',
     NOW() - INTERVAL '3 days'),

    ('00000000-0000-4000-a000-000000000201',
     '00000000-0000-4000-a000-000000000101',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000101/00000000-0000-4000-a000-000000000201',
     'demo-seed-hash-1010000000000000000000000000000000000000000000000000000',
     2048, 'text/csv', 'manual/1',
     NOW() - INTERVAL '2 days'),

    ('00000000-0000-4000-a000-000000000202',
     '00000000-0000-4000-a000-000000000102',
     '00000000-0000-4000-a000-000000000001', 1,
     'organizations/00000000-0000-4000-a000-000000000001/evidence/00000000-0000-4000-a000-000000000102/00000000-0000-4000-a000-000000000202',
     'demo-seed-hash-1020000000000000000000000000000000000000000000000000000',
     1024, 'application/pdf', 'manual/1',
     NOW() - INTERVAL '1 days');

-- -----------------------------------------------------------------------------
-- 3. Mappings.
--
--    - EV-100 (Access Review) is HUMAN_CONFIRMED COVERED for CC6.3
--      → CC6.3 shows as COVERED on the dashboard.
--    - EV-101 (IAM Users)     is AI_SUGGESTED  PARTIAL for CC6.1
--      → CC6.1 shows as NEEDS_REVIEW.
--    - EV-102 has no mapping yet.
-- -----------------------------------------------------------------------------

INSERT INTO evidence_control_mappings (id, organization_id, evidence_id,
                                       control_id, mapping_type, classification,
                                       confidence, reason, created_by)
SELECT '00000000-0000-4000-a000-000000000300'::uuid,
       '00000000-0000-4000-a000-000000000001'::uuid,
       '00000000-0000-4000-a000-000000000100'::uuid,
       (SELECT id FROM controls WHERE code = 'CC6.3'),
       'HUMAN_CONFIRMED', 'COVERED', 1.000,
       'Reviewer confirmed: signed quarterly access review is present.',
       '00000000-0000-4000-a000-000000000011'::uuid;

INSERT INTO evidence_control_mappings (id, organization_id, evidence_id,
                                       control_id, mapping_type, classification,
                                       confidence, reason, created_by)
SELECT '00000000-0000-4000-a000-000000000301'::uuid,
       '00000000-0000-4000-a000-000000000001'::uuid,
       '00000000-0000-4000-a000-000000000101'::uuid,
       (SELECT id FROM controls WHERE code = 'CC6.1'),
       'AI_SUGGESTED', 'PARTIAL', 0.720,
       'Evidence lists current IAM users but does not demonstrate a periodic review or approval trail.',
       NULL;

-- -----------------------------------------------------------------------------
-- 4. Review that approved EV-100.
-- -----------------------------------------------------------------------------

INSERT INTO evidence_reviews (id, organization_id, evidence_id, reviewer_id,
                              decision, comments)
VALUES ('00000000-0000-4000-a000-000000000400',
        '00000000-0000-4000-a000-000000000001',
        '00000000-0000-4000-a000-000000000100',
        '00000000-0000-4000-a000-000000000011',
        'APPROVED',
        'Signed by security lead; scope and dates check out.');

-- -----------------------------------------------------------------------------
-- 5. Audit events for the flow above.
-- -----------------------------------------------------------------------------

INSERT INTO audit_events (organization_id, actor_user_id, event_type,
                          entity_type, entity_id, metadata) VALUES
    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000010',
     'USER_CREATED', 'user',
     '00000000-0000-4000-a000-000000000010', '{"seed":true}'),

    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000010',
     'USER_CREATED', 'user',
     '00000000-0000-4000-a000-000000000011', '{"seed":true,"role":"REVIEWER"}'),

    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000010',
     'EVIDENCE_CREATED', 'evidence',
     '00000000-0000-4000-a000-000000000100',
     '{"seed":true,"source":"MANUAL_UPLOAD"}'),

    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_MAPPED', 'evidence_control_mapping',
     '00000000-0000-4000-a000-000000000300',
     '{"seed":true,"controlCode":"CC6.3","type":"HUMAN_CONFIRMED"}'),

    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000011',
     'EVIDENCE_REVIEWED', 'evidence',
     '00000000-0000-4000-a000-000000000100',
     '{"seed":true,"decision":"APPROVED"}'),

    ('00000000-0000-4000-a000-000000000001',
     '00000000-0000-4000-a000-000000000010',
     'AI_ANALYSIS_CREATED', 'evidence',
     '00000000-0000-4000-a000-000000000101',
     '{"seed":true,"provider":"stub","model":"stub-1","promptVersion":"evidence-mapping/v1"}');

COMMIT;

-- =============================================================================
-- Verify from psql:
--   SELECT status, count(*)
--     FROM evidence
--    WHERE organization_id = '00000000-0000-4000-a000-000000000001'
--    GROUP BY status;
--
--   -- On the API/UI:
--   -- login as demo-owner@syncpoint.local / demo-password-2026
--   -- dashboard should show 1 COVERED, 1 NEEDS_REVIEW, 13 MISSING
-- =============================================================================
